### ISSUE TITLE
IOR fails on call to statfs()

### ISSUE THREAD

**Issue by CamStan** [LLNL/UnifyFS#160]
When using [IOR](https://github.com/hpc/ior) to write to a test file to a non-existent mount point (i.e., /unifycr), IOR calls statfs(). 
```
srun -N4 -n4 ior -w -r -o /unifycr/testfile
```
This resulted in an IOR error as we currently do not have a wrapper for this function.
```
ior ERROR: unable to statfs() file system, errno 2, No such file or directory (utilities.c:376)
application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
```

IOR user guide found [here](https://github.com/hpc/ior/blob/master/doc/USER_GUIDE).

**Comment by adammoody** [comment]
Nice find, @CamStan!  Assuming this is not already done or underway by someone else, this would be a good introduction to creating and testing a new wrapper.  I can help you work through that.

**Comment by CamStan** [comment]
UnifyFS has been run with IOR successfully since this issue. Warnings/errors can possibly still show up when doing so, but setting `UNIFYFS_CLIENT_SUPER_MAGIC=off` should work around this.
