### ISSUE TITLE
READ_BUF_SZ is 1 GB

### ISSUE THREAD

**Issue by boehms** [LLNL/UnifyFS#161]
In unifycr_const.h READ_BUF_SZ is defined to one GB, this seems to be excessive. Should we change this to a smaller buffer size or make it a runtime parameter?

It is used in unifier_service_mgr.c to allocate a buffer. The buffer seems to be quite big, especially if testing is done on VM's with limited memory.

**Comment by MichaelBrim** [comment]
This problem should go away in the Hg port, but in the meantime we need to understand if there are any other assumptions/definitions that are related. My suggestion for now is to try 64MB.

**Comment by MichaelBrim** [comment]
This constant no longer exists, closing.
