### ISSUE TITLE
Need a solution to compute/return file size

### ISSUE THREAD

**Issue by adammoody** [LLNL/UnifyFS#205]
In order to compute file size, one effectively has to compute the maximum extent offset across all nodes that are storing bytes for a given file, or equivalently, the maximum offset across keys.  This is not currently done.  Once laminated, the file size could be cached, perhaps with the file metadata.  Or we could update the file size on each fsync rpc by computing the max offset with the max known file size.

We're currently fetching metadata to get the file size to then determine whether a read extends past the end of a file, but this assumes that we actually have the correct file size, e.g,:

https://github.com/LLNL/UnifyCR/blob/13a8a327de9573895f194adff9744a0de70e1389/client/src/unifycr-sysio.c#L929

**Comment by MichaelBrim** [comment]
Note that in dev branch, I had to disable that EOF calculation as it caused errors for reads. When we solve this issue, we'll need to re-enable.

**Comment by adammoody** [comment]
https://github.com/LLNL/UnifyCR/pull/261

**Comment by adammoody** [comment]
@MichaelBrim , this should be working and I was hoping to close the issue.  However, since you mentioned you disabled something that should be reenabled, can you please review and sign off on this?

**Comment by MichaelBrim** [comment]
@adammoody that code was restored by Tony in one of his recent PRs. Should be ok to close this.

**Comment by adammoody** [comment]
Great, thanks for verifying.
