### ISSUE TITLE
ensure that all read wrappers call fd_logreadlist

### ISSUE THREAD

**Issue by adammoody** [LLNL/UnifyFS#216]
Not all read wrappers are calling unifycr_fd_logreadlist, unifycr_stream_read() in unifycr-stdio.c for example.  There could be others.

**Comment by adammoody** [comment]
@tonyhutter , with your change, I think we may have all functions going through a common read path now.  Can you please check if that's the case?  And if so, let's close out this issue.

**Comment by CamStan** [comment]
Considering resolved. Reopen if anything was missed.
