### ISSUE TITLE
Add local key/value store to service reads of local data

### ISSUE THREAD

**Issue by adammoody** [LLNL/UnifyFS#252]
We should add support for a local key/value store that can be used to look up index info for data that are stored locally on the node.  Currently, our write/read paths are asymmetrical.

On a write, a client copies data to memory in its superblock or it pwrites the data to its spillover file while recording the key/value info that tracks the location of the data in a local memory region.  All of this is local to the client, so that a write does not hit the server at all (until close or fsync).

On a read, it sends an rpc to the server, and the server does an MDHIM lookup for the key/value pairs describing the location of the data.  The server then hands the task off to its request delegator thread, which sends a request to read the data to a service manager thread via MPI, which reads the data and sends the read data back via MPI to the request delegator thread, which then copies the data to shared memory, and finally notifies the client that the read data is available in shared memory.

In the case of checkpoint / restart, where a process is likely to only (or mostly) read the data it wrote, we could avoid this cost by having the client keep a local key/value store of the data that it wrote.  In this case, the client would first check its local key/value store for the index information and service the read locally if possible.  For any bytes it does not know about via its local key/value store, it would fall back to the current method of sending an rpc to the server.  If a process only reads back data that it wrote, then this would enable it to entirely avoid communication with the server, so that reads should be about as fast as the writes.

**Comment by adammoody** [comment]
@boehms , as you're working on defining the new metadata api, we could benefit from your thoughts here, too.

**Comment by boehms** [comment]
Do we need a key value store for this? If the data is stored in the superblock, we should be able to look it up there and only issue a server request if we cannot find the entry.

**Comment by adammoody** [comment]
@boehms , right, we will have all of the index info saved somewhere in the superblock.  My thinking is that we'll probably want some data structure to cache the index info for faster lookups.  Without that, we'd have to linearly scan the index entries from the list where they're stored, whereas keeping the index data in some type of tree or hash structure would provide for faster lookups.  We'll also want to be able to do range-style lookups like we do in MDHIM now, e.g., return the set of all keys covering the range of logical file offsets from 0MB-10MB.

**Comment by adammoody** [comment]
Added mechanism to do this in client with https://github.com/LLNL/UnifyFS/pull/434
Server version of same thing coming in https://github.com/LLNL/UnifyFS/pull/427
