### ISSUE TITLE
Abstracting the client superblock and UnifyCR context

### ISSUE THREAD

**Issue by sandrain** [LLNL/UnifyFS#297]
Currently, there exists a number of global variables defined in `client/src/unifycr.c`. Specifically, all necessary variables are scattered through multiple variables (with confusing naming at times). It would be better if we have a separate data structure to hold all necessary information within a single structure, possibly:

```
/* This is preliminary, not from thorough examination */

/* for file system internal data structures in the shm superblock */
struct unifycr_super_info {
};

/* other information necessary for runtime */
struct unifycr_ctx {
  struct unifycr_super_info *super;
  int app_id;
};
```

Also, refactoring superblock and context can be seen as a subtask to reorganize/redesign the client module, which was previously discussed, i.e., #262, #257, and FUSE support.

**Comment by boehms** [comment]
I started some work on this a while back, not sure if this is still relevant, but you ban find it [here](/boehms/UnifyCR/tree/topic/cleanup-client-context)

**Comment by MichaelBrim** [comment]
This will be fixed with the new client API work, closing this issue.
