### ISSUE TITLE
Multi-rank local file size bug

### ISSUE THREAD

**Issue by CamStan** [LLNL/UnifyFS#324]
### Describe the problem you're observing
When running the [write](https://github.com/LLNL/UnifyCR/blob/dev/examples/src/write.c) and [writeread](https://github.com/LLNL/UnifyCR/blob/dev/examples/src/writeread.c) examples (mostly tested with gotcha run mode, but static does this as well) with more than one process, I get an error that looks like I simply ran out of spillover space.

```
unifycr_chunk_alloc: spill-over device out of space (15)
[1] write() failed (errno=28, No space left on device)
[1] write req 0 failed (errno=28, No space left on device)
[1] write() failed (errno=28, No space left on device)
[1] write req 1 failed (errno=28, No space left on device)
⋮
```
However, not always on the first attempt (but mostly) and always every attempt after, this occurs when writing a file that would only be 64MB in size (each process writing two chunks of 16MB a piece) and when there is multiple GB of spillover space available.

Notice this error was only thrown by `rank 1` and never by `rank 0`.

### Describe how to reproduce the problem
Set the following environment variables before running the server:
```
export UNIFYCR_DAEMONIZE=off
export UNIFYCR_SPILLOVER_ENABLED=yes
export UNIFYCR_DEBUG=on
export UNIFYCR_LOG_VERBOSITY=5
export UNIFYCR_SPILLOVER_SIZE=1073741824
export UNIFYCR_SPILLOVER_META_DIR=/path/to/ssd
export UNIFYCR_SPILLOVER_DATA_DIR=/path/to/ssd

# start the server
/path/to/bin/unifycr start -m /unifycr -e /path/to/bin/unifycrd &
```
While debugging, I used the `write-gotcha` example with either 1 node and 2 processes or 2 nodes and 1 process on each:
```
jsrun -n2 -a1 -c18 -r1 /path/to/libexec/write-gotcha -p n1 -n 2 -c 4096 -b 16384 -v -f testfile
```

### Bug 1
I'm not familiar with how all this should work as of yet, so here is what I observed. After stepping through the code multiple times, I believe I've narrowed down the cause and potentially another related bug. 

In [write.c](https://github.com/LLNL/UnifyCR/blob/dev/examples/src/write.c), on `rank 0`, [test_create_file](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/examples/src/write.c#L152) -> [open](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/examples/src/testutil.h#L885) -> [__wrap_open](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr-sysio.c#L716) -> [unifycr_fid_open](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr-sysio.c#L735)  where a new file gets created:
https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr.c#L1346-L1349
During this process, the global file meta is set: [unifycr_set_globalfile_meta](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr.c#L1378) -> [invoke_client_metaset_rpc](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr.c#L813) which fills in an input struct  for margo, but only sets three things (and has a TODO) - **Bug 1:**
https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/margo_client.c#L259-L264
Upon inspecting`unifycr_metaset_in_t in`, the `size` field was rather large:

![margo-in](https://user-images.githubusercontent.com/12384825/59545139-36c89400-8ecf-11e9-89ca-f3f82218e2a7.png)

### Bug 2(?)
After `rank 0` had created the file, `rank 1` would then be able to open it: [test_create_file](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/examples/src/write.c#L152) -> [test_open_file](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/examples/src/testutil.h#L900) -> [open](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/examples/src/testutil.h#L825) -> [__wrap_open](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr-sysio.c#L716) -> [unifycr_fid_open](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr-sysio.c#L735) where a `gfid` is found, but a local `fid` is not
https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr.c#L1295-L1299

However, when the global file id is found, it retrieves the metadata set by `rank 0`: [unifycr_get_global_file_meta](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr.c#L1273-L1274) -> [invoke_client_metaget_rpc](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr.c#L830)
https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/margo_client.c#L316-L324
However, since `rank 0` didn't set all the file attributes, the large values get retrieved by `rank 1`:

![margo-out](https://user-images.githubusercontent.com/12384825/59545312-7e501f80-8ed1-11e9-8cd4-6c2278d2a246.png)

where the values of `*gfattr` are set in [unifycr_get_global_file_meta](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr.c#L832) -> [unifycr_fid_open](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr.c#L1273-L1274).
Then, what seems to be **bug 2**, the `rank 1` local file size gets set to the large global file size:
https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr.c#L1319

### Large file size links back to original problem
The spillover error was then showing up because of the large `rank 1` file size. In [write.c](https://github.com/LLNL/UnifyCR/blob/dev/examples/src/write.c), on `rank 1`: [issue_write_req_batch](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/examples/src/write.c#L172) -> [issue_write_req](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/examples/src/write.c#L172) -> [write](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/examples/src/write.c#L172) -> [__wrap_write](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr-sysio.c#L1053) -> [unifycr_fd_write](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr-sysio.c#L1070) where the file size is retrieved:
https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr-sysio.c#L614

Since `meta->storage == FILE_STORAGE_LOGIO` (which I don't know if it should be in this case) `unifycr_fid_extend` then gets called with `newpos` being set using the large file size:
https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr-sysio.c#L635-L637
 -> [unifycr_fid_store_fixed_extend](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr.c#L1142) -> [unifycr_chunk_alloc](https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr-fixed.c#L541).

However, because the file size was so large, `additional` becomes large and this `while` loop runs until all available space in memory and spillover is allocated before the first write happens:
https://github.com/LLNL/UnifyCR/blob/52c2d7d9f36df1d3e8247d6ba0ef77802bb9313d/client/src/unifycr-fixed.c#L534-L541

**Comment by adammoody** [comment]
@CamStan , is this resolved now?

**Comment by CamStan** [comment]
Yup!
