### ISSUE TITLE
Global size vs local size (log size)

### ISSUE THREAD

**Issue by adammoody** [LLNL/UnifyFS#327]
For a process that opens a file for writing, but does not create it, it was discovered that the size field returned in the stat structure for the file affected the amount of chunks allocated on the calling process when it tried to write data to the file (#324) .  The global size field should not affect the amount of chunks a process has locally contributed to the file.  We need to track down and fix that mismatch.

**Comment by adammoody** [comment]
My current suggestion would be to divide our internal structures into two.  We should have one structure that only tracks local information about a file, e.g., current size of the local log.  We should have a separate structure that tracks global information.  Perhaps the global info would always come from the server.  The global info could be cached on the server once the file has been laminated.

We are currently using a single structure to represent both, and it's easy to get fields mixed up (e.g., size vs log_size).

**Comment by adammoody** [comment]
@CamStan , since you have a good start on this one, would you mind chasing it down?

**Comment by CamStan** [comment]
Absolutely!

**Comment by adammoody** [comment]
@tonyhutter , I think we still have a few locations where the code is mixing local size and global size in a bad way.

Under CRUISE, a file's logical file size and the amount of file data stored in chunks was the same number, because shared files were not supported and files were assumed to be dense (we made no sparse file storage optimizations).  The unifyfs_fid_size() function returned this single value.

However, with UnifyFS, these two values are often different.  We need to review the code and determine which value is really needed and make sure we're using the appropriate one at every point where unifyfs_fid_size() is called.

For example, during read, we use unifyfs_fid_size() to query the global file size to know not to read past the EOF:
https://github.com/LLNL/UnifyFS/blob/dev/client/src/unifyfs-sysio.c#L557

But during a write, we use unifyfs_fid_size() to determine where the next bytes should be stored in the log to know whether to allocate more chunks or not:
https://github.com/LLNL/UnifyFS/blob/dev/client/src/unifyfs-sysio.c#L614

Let's split this function into two: one that returns the last byte written to the local log, and another that returns the global file size.  Then let's check every existing call and replace it with the appropriate new version.

Similarly, I think there are parts of the code that skip calling unifyfs_fid_size and refer directly to "size" or "log_size" fields in our structure. Let's review each of those references, as well and consider replacing them with calls to one of the new functions.

**Comment by tonyhutter** [comment]
Ok, I'll take another look

**Comment by tonyhutter** [comment]
Just doing some quick grepping, I see the following places where unifyfs_fid_size()/meta->size/meta->log_size are used:
```
unifyfs-stdio.c:unifyfs_stream_write()
	- Call unifyfs_fid_size() check size for append mode

unifyfs-stdio.c:unifyfs_fseek()
	- Call unifyfs_fid_size() to seek to end of file.

unifyfs-sysio.c:unifyfs_fd_write()
	- Update meta->size after a write.

unifyfs.c:unifyfs_fid_extend()
	- Look at meta->size to see if we need to expand the file to satisfy a really
big 'length' value.

unifyfs.c:unifyfs_fid_truncate()
	- Look at meta->size and set it for truncating the file

unifyfs.c:unifyfs_fid_open()
	- Cache global file size in meta->size if laminated
	- If opening a laminated file for O_APPEND, set the file position to
meta->size (which is is unnecessary since open(O_APPEND,...) on a laminated
file is not supported).

unifyfs.c:unifyfs_set_global_file_meta()
	- Use meta->size to set global file size during a lamination

unifyfs.c:unifyfs_fid_create_file
	- Set meta->size to 0

unifyfs.c-dirops.c:UNIFYFS_WRAP(opendir)
	- Set meta->size to directory size

unifyfs.c-dirops.c:UNIFYFS_WRAP(opendir)
	- Set meta->log_size to 0

unifyfs-sysio.c:unifyfs_fd_write()
	- Set meta->log_size to pos + count

unifyfs.c:unifyfs_fid_create_file()
	- Set meta->log_size to 0
```
Strangely, it appears that meta->log_size is written but never read.

At first glance, it seems that we're ok using meta->size for both the local and global file size, since the "is_laminated" checks would prevent it from ever being used incorrectly.  For example, we know that meta->size will only be the local size when used for writes because earlier is_laminated checks would prevent writing to a laminated file.  I don't see any issue for reads either - a read of a local file should EOF at the end of the local file size, and a read of a laminated file should EOF at the end of the global size (we assume the users wont laminate a file in the middle of a read).  I'm not 100% convinced that there isn't some edge case I'm not considering though.

**Comment by adammoody** [comment]
I get nervous about having one field in a structure represent two different concepts, with its interpretation depending on the value of another field.  The code will be more explicit and easier to read and debug if we use two different fields to represent those two different concepts.

Let's use meta->size to represent the global file size, and let's use meta->log_size to represent the current size of the data log.

Looking at your list and grouping some related references, I think we have the following:

```
unifyfs-stdio.c:unifyfs_stream_write()
	- Call unifyfs_fid_size() check size for append mode
(query of global file size)

unifyfs-stdio.c:unifyfs_fseek()
	- Call unifyfs_fid_size() to seek to end of file.
(query of global file size)

unifyfs-sysio.c:unifyfs_fd_write()
	- Update meta->size after a write.
(need to update log size instead)

unifyfs-sysio.c:unifyfs_fd_write()
	- Set meta->log_size to pos + count
(unsure if this is the proper value, see above)

unifyfs.c:unifyfs_fid_extend()
	- Look at meta->size to see if we need to expand the file to satisfy a really
big 'length' value.
(need to refer to log size instead)

unifyfs.c:unifyfs_fid_truncate()
	- Look at meta->size and set it for truncating the file
(need to update global size, but truncate is also used to free or add chunks to the log, so this is not straight forward, related issue open on how to deal with truncate)

unifyfs.c:unifyfs_fid_open()
	- Cache global file size in meta->size if laminated
	- If opening a laminated file for O_APPEND, set the file position to
meta->size (which is is unnecessary since open(O_APPEND,...) on a laminated
file is not supported).
(both of these are using global file size)

unifyfs.c:unifyfs_set_global_file_meta()
	- Use meta->size to set global file size during a lamination
(set global file size, not sure we should be using this field though unless it has been set with filesize_rpc)

unifyfs.c:unifyfs_fid_create_file
	- Set meta->size to 0
(setting global file size)

unifyfs.c:unifyfs_fid_create_file()
	- Set meta->log_size to 0
(initializing log to 0 bytes)

unifyfs.c-dirops.c:UNIFYFS_WRAP(opendir)
	- Set meta->size to directory size

unifyfs.c-dirops.c:UNIFYFS_WRAP(opendir)
	- Set meta->log_size to 0
```

**Comment by craigsteffen** [comment]
It looks like the unifyfs_filemeta_t contains fields "size" and "log_size",
and as you all have been saying they are sometimes harvested using
functions but occasionally pulled out using functions.  When we really
decide to nail this down, I would propose doing the following to minimize
the chances of missing a reference.  Replace both of those fields with two
better-named fields and a third named field for global file size.  That
way, both of the old names are gone, and anything using them at all will
have to be changed.  We'll have to also check every instance of calling the
functions that pull those numbers out.

In other words, I would propose changing the top part of that struct to be
something like:

*typedef* *struct* {

    off_t local_logical_size;    /* logical size of the amount of the file
written from the local rank */

    off_t local_log_size;        /* size of the write log of the data
written from the local rank */
                                                            /* if the file
is written with no seeks after the first write, the last two will both be
total bytes written by local rank */
    off_t global_logical_size;  /* total file size summed over all data
over all ranks.  Only valid if file is completed being laminated */
.......

We could change the struct to this and then fix everywhere that breaks in
the compile, being careful to make sure that everything is consistent with
the storage and writing model.

Craig Steffen

**Comment by tonyhutter** [comment]
> (query of global file size)

@adammoody just for clarification of you comments - are you assuming the file has been sync()ed before querying the global file size?  As I understand it (but have not tested it), the global file size on a un-synced file is going to be 0.  If so, then we really have three file sizes cases:

1. Written locally but never synced or laminated.  Global file size is 0, local size is correct.

2. Written locally and synced, but not laminated.  Global file size may be correct, local size may be correct.  It all depends on how many writers there are and if they're all synced or not.

3. Written locally, synced, and laminated.  Global file size is correct, local size may be correct if its a single writer only.

**Comment by tonyhutter** [comment]
Also I believe open(O_APPEND) is currently allowed on non-laminated files (synced or un-synced).  Is that your understanding as well?  If so, is that the correct behaviour?

**Comment by adammoody** [comment]
Right, we can't support append mode, since we don't keep track of the current file size.  It's interesting that the man page for open(2) also mentioned that NFS may not support O_APPEND:
```
O_APPEND
  The  file  is opened in append mode.  Before each write(2),
  the file offset is positioned at the end of the file, as if with lseek(2).
  O_APPEND may lead to corrupted files on NFS file systems
  if more than one process appends data to a file at once.
  This is because NFS does not support appending to a file,
  so the client kernel has to simulate it, which can't be done
  without a race condition.
```
We could return an error if someone tries to open a file with O_APPEND.  That's probably ok, since I doubt O_APPEND is a common thing in parallel jobs.  However, if that breaks too many codes, we could also silently ignore it.

Either way, we need to be sure we document that people should not do it.

**Comment by adammoody** [comment]
To get started, I think it's fine to always return 0 for the file size if the file is not laminated, and then return the real file size once laminated.

One level up from that would be to always call the filesize_rpc and return its value before lamination.  After lamination, the file size could be cached locally, and the call to the filesize_rpc could be skipped.  This option would enable something that could return the actual file size, but at a higher cost.  For example, a code could do the following:
```
fd = open(path)
write(fd)
fsync(fd)
close(fd)
MPI_Barrier(MPI_COMM_WORLD)
if (rank == 0) {
  // because all procs call fsync,
  // and we know the fsync on all procs have completed due to the barrier
  // this stat could actually return the correct size, even before lamination  
  stat(path)
}
```

**Comment by adammoody** [comment]
Fixed with https://github.com/LLNL/UnifyFS/pull/377
