### ISSUE TITLE
Bug on the parallel file transfer

### ISSUE THREAD

**Issue by sandrain** [LLNL/UnifyFS#335]
The parallel transfer does not write the last block (64KB) correctly.

**Comment by craigsteffen** [comment]
As I spin up my work on this project from NCSA, this is the first thing I'm going to try to verify, isolate, and if possible, fix.

**Comment by adammoody** [comment]
Due to this issue https://github.com/LLNL/UnifyFS/issues/368?

**Comment by adammoody** [comment]
@sandrain , @craigsteffen , I'm assuming this is the same as https://github.com/LLNL/UnifyFS/issues/368, so closing as duplicate.  If you disagree, let's reopen it.
