### ISSUE TITLE
./configure: line 15532: Echo: command not found 

### ISSUE THREAD

**Issue by tonyhutter** [LLNL/UnifyFS#338]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       | Fedora
OS Version             | 30
Architecture           | x86-64
UnifyCR Version        | dev

### Describe the problem you're observing
I'm seeing `Echo: command not found`  on Fedora 30:
```
./configure
...
Checking whether not-found responds to '-showme:compile'... no
Checking whether not-found responds to '-showme'... no
Checking whether not-found responds to '-compile-info'... no
Checking whether not-found responds to '-show'... no
./configure: line 15532: Echo: command not found
checking for leveldb_open in -lleveldb... no
````

The problem goes away when I comment out `LX_FIND_MPI` in `configure.ac`.  Note that I'm building without MPI installed.

### Describe how to reproduce the problem
```
./configure
```

**Comment by adammoody** [comment]
Yeah, that comes from a typo in this line:

**Comment by adammoody** [comment]
Fixed with https://github.com/LLNL/UnifyFS/commit/6e9e72d3217c48ecda4fb08cdacf5b8045bb4837
