### ISSUE TITLE
Write example file size error on larger file

### ISSUE THREAD

**Issue by CamStan** [LLNL/UnifyFS#365]
One write example for writing a shared file from our integration tests is currently failing due to the file size check failing. It fails on both lsf and toss for both the gotcha and static versions.

#### Important
This example doesn't start failing for me until I use 8 processes. Ran it on 1 node w/ 8 processes, 2 nodes w/ 4 processes each, 4 nodes w/ 2 processes each, and 8 nodes with 1 process each and got the same failure each time.

Haven't tested this, but if it's directly related to the size of the file, or the size each process is writing, it's possible that increasing the file size even more will reduce the number of processes needed before hitting the error.

----

Only configs I set before starting the server were:
```Bash
export UNIFYFS_DAEMONIZE=off
export UNIFYFS_SPILLOVER_META_DIR=/dev/shm
export UNIFYFS_SPILLOVER_DATA_DIR=/dev/shm
```
and started the server:
```Bash
/path/to/UnifyFS/install/bin/unifyfs start -S /path/to/shared/dir -e /path/to/UnifyFS/install/bin/unifyfsd &
```

Then I ran the example, having each of the 8 processes write 512MB (using two nodes here):
```Bash
jsrun -a4 -c20 -r1 -n2 /path/to/UnifyFS/install/libexec/write-static -p n1 -n 32 -c 1048576 -b 16777216 -a 0 -m /unifyfs -f write-static_pn1_n32_c1MB_b16MB.app
```
or
```Bash
srun -N2 -n8 /path/to/UnifyFS/install/libexec/write-static -p n1 -n 32 -c 1048576 -b 16777216 -a 0 -m /unifyfs -f write-static_pn1_n32_c1MB_b16MB.app
```

This results in something like:
```
[0] ERROR - file size check failed - actual size is 0 B, expected 4294967296 B (errno=5, Input/output error)

I/O pattern:               N-to-1
I/O block size:            16384.00 KiB
I/O request size:          1024.00 KiB
Number of processes:       8
Each process wrote:        512.00 MiB
Total data written:        4096.00 MiB
Maximum write time:        0.365366 sec
Maximum sync time:         0.028753 sec
Aggregate write bandwidth: 11634.024 MiB/s
Effective write bandwidth: 11210.676 MiB/s
 (errno=5, Input/output error)
```

The write does appear to work though as the subsequent read seems to work, aside from throwing the same file size error:
```Bash
srun -N2 -n8 /path/to/UnifyFS/install/libexec/read-static -p n1 -n 32 -c 1048576 -b 16777216 -a 0 -v -m /unifyfs -f write-static_pn1_n32_c1MB_b16MB.app
```
results in something like:
```
[0] ERROR - file size check failed - actual size is 0 B, expected 4294967296 B

I/O pattern:               N-to-1
I/O block size:            16384.00 KiB
I/O request size:          1024.00 KiB
Number of processes:       8
Each process wrote:        512.00 MiB
Total data written:        4096.00 MiB
Maximum read time:         0.994544 sec
Maximum check time:        0.000001 sec
Aggregate read bandwidth:  5015.018 MiB/s
Effective read bandwidth:  4118.470 MiB/s
```

**Comment by CamStan** [comment]
@tonyhutter, this is the example that is failing when running the integration tests.

**Comment by tonyhutter** [comment]
> [0] ERROR - file size check failed - actual size is 0 B, expected 4294967296 B (errno=5, Input/output error)

I was able to reproduce this.  It appears that the `chmod()` to laminate the file is failing.

```
2019-09-24T15:55:35 tid=46019 @ invoke_client_filesize_rpc() [margo_client.c:411] Got response ret=4294967295
2019-09-24T15:55:35 tid=46019 @ __chmod() [unifyfs-sysio.c:2423] chmod: couldn't get the global file size on laminate
[0] done laminating /unifyfs/write-static_pn1_n32_c1MB_b16MB.app, chmod() = -1 (errno=5, Input/output error)
```
More specifically, the chmod()'s call to `invoke_client_filesize_rpc()` is returning -1:

```C
        /*
         * We're laminating. Calculate the file size so we can cache it
         * (both locally and on the server).
         */
        ret = invoke_client_filesize_rpc(gfid, &meta->size);
        if (ret) {
            LOGERR("chmod: couldn't get the global file size on laminate");
            errno = EIO;
            return -1;
        }
        meta->is_laminated = 1;
    }
```
Drilling that down, its `margo_get_output()` that's returning a bad `out.ret` value:

```C
/* invokes the client filesize rpc function */
int invoke_client_filesize_rpc(int gfid,
                               size_t* outsize)
{
    int32_t ret;
    hg_handle_t handle;

    if (NULL == client_rpc_context) {
        return UNIFYFS_FAILURE;
    }

    /* get handle to rpc function */
    hg_return_t hret = margo_create(client_rpc_context->mid,
                                    client_rpc_context->svr_addr,
                                    client_rpc_context->rpcs.filesize_id,
                                    &handle);
    assert(hret == HG_SUCCESS);

    /* fill in input struct */
    unifyfs_filesize_in_t in;
    in.app_id         = (int32_t)app_id;
    in.local_rank_idx = (int32_t)local_rank_idx;
    in.gfid           = (int32_t)gfid;

    /* call rpc function */
    LOGDBG("invoking the filesize rpc function in client");
    hret = margo_forward(handle, &in);
    assert(hret == HG_SUCCESS);

    /* decode response */
    unifyfs_filesize_out_t out;
    hret = margo_get_output(handle, &out);
    assert(hret == HG_SUCCESS);
    ret = out.ret;
    LOGDBG("Got response ret=%" PRIu32, ret);
...
```
So we can't get the global file size following this test for some reason...

**Comment by adammoody** [comment]
I'll take a look at this problem this week.

**Comment by adammoody** [comment]
This is happening because we have a hard-coded limit on the number of key/value pairs we can process at one time when looking up file extents:

unifyfs_filesize_rpc(() --> rm_cmd_filesize() --> unifyfs_get_file_extents()
https://github.com/LLNL/UnifyFS/blob/3e2c859142082ec014f64c8409a8334eec254dcd/server/src/unifyfs_metadata.c#L433

The MAX_META_PER_SEND is set to 4*KiB (4096) here:
https://github.com/LLNL/UnifyFS/blob/3e2c859142082ec014f64c8409a8334eec254dcd/common/src/unifyfs_const.h#L59

There is a second hard-coded constant involved here:
https://github.com/LLNL/UnifyFS/blob/3e2c859142082ec014f64c8409a8334eec254dcd/server/src/unifyfs_request_manager.c#L508

That happens to also be defined as 4*KiB, perhaps by luck here:
https://github.com/LLNL/UnifyFS/blob/3e2c859142082ec014f64c8409a8334eec254dcd/common/src/unifyfs_const.h#L92

That's all carryover from my cut-and-paste of this logic from the read code.  I'll think about how to fix that up for the filesize, but we probably also need to revisit this for the read.  For example, I wonder if we handle really large reads, or a read that happens to span lots of key/value pairs (over 4096).
