### ISSUE TITLE
fread() not implemented for FILE_STORAGE_LOGIO

### ISSUE THREAD

**Issue by tonyhutter** [LLNL/UnifyFS#367]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       | all
OS Version             | all
Architecture           | all
UnifyFS Version        | all

### Describe the problem you're observing
`fread()` needs to be implemented.  More specifically, it needs to be implemented for the `meta->storage == FILE_STORAGE_LOGIO` case, which is the default right now.  An `fread()` currently returns an error. 

### Describe how to reproduce the problem
Do an `fread()`

### Include any warning or errors or relevant debugging data
The `fread()` call path looks like this:

```C
UNIFYFS_WRAP(fread)
	unifyfs_stream_read()
		unifyfs_fd_read()
			unifyfs_fid_read():

			/* determine storage type to read file data */
    			if (meta->storage == FILE_STORAGE_FIXED_CHUNK) {
			        /* file stored in fixed-size chunks */
				rc = unifyfs_fid_store_fixed_read(fid, meta, pos, buf, count);
			} else {
			        /* unknown storage type */
			        rc = (int)UNIFYFS_ERROR_IO;
			}
```

**Comment by tonyhutter** [comment]
Note that `read()` does work correctly.

**Comment by adammoody** [comment]
@tonyhutter , can you work this issue along with the read() fix:

**Comment by tonyhutter** [comment]
Yea, I have a patch that makes it so both `read()` and `fread()` call a modified `unifyfs_fd_read()` and it seems to work.  Assigning bug to myself.

**Comment by tonyhutter** [comment]
I'll test to see if my fix also helps #368

**Comment by adammoody** [comment]
Nice!  Already a step ahead.  It looks like this logic will help catch the EOF case:

https://github.com/LLNL/UnifyFS/blob/7f908fe98f7dd64c9797b39f7af23ac3968cd6ad/client/src/unifyfs-sysio.c#L555

**Comment by MichaelBrim** [comment]
Note: this is one step of issue #296
