### ISSUE TITLE
Change fid to gfid in read requests

### ISSUE THREAD

**Issue by adammoody** [LLNL/UnifyFS#395]
The read requests contain a field named ```fid```.

https://github.com/LLNL/UnifyFS/blob/feaca4e9c086c6b9ffaebc0583344c3b3fe7e89e/client/src/unifyfs-internal.h#L300

We eventually need this to be the global file id, which we call ```gfid```.  Let's change the field name to be gfid to avoid confusion.

There is a place here where we convert read requests from using fid to gfid.

https://github.com/LLNL/UnifyFS/blob/feaca4e9c086c6b9ffaebc0583344c3b3fe7e89e/client/src/unifyfs-sysio.c#L1798

Let's rewrite the read path to use global file id everywhere, so use gfid instead of fid from the instant the read request is created rather than switching part way through.

**Comment by craigsteffen** [comment]
Adam,

It looks like there's a typo in the title.  The text is fairly clear, but
the title says "Change fid to fid in...."

I wouldn't normally worry about a typo, but in this case since the those
words are at the heart of the meaning of the change, it's probably best to
be fixed.

Craig

**Comment by adammoody** [comment]
@craigsteffen , yep.

**Comment by adammoody** [comment]
@clmendes , sorry that I stole this one from you.  For some reason, this item was nagging me, and I figured I'd rest better to just knock it out.
