### ISSUE TITLE
Design: flattening writes

### ISSUE THREAD

**Issue by tonyhutter** [LLNL/UnifyFS#409]
Currently we store all writes in a log and send them all to the server on fsync().  This gives us really fast writes since we can just append our write to the end of the log.  The downside is that if you do an overwrite of existing data, that also gets synced to the server.  So if you did 100 one byte writes to the same offset in the file, all 100 writes get sent to the server, instead of one single  write with the final value.  Furthermore, to read that last byte you need to replay all 100 writes, making reads slow.

I'm working on a update to Unify that would store all the writes in a segment tree.  This would allow us to get rid the overlapping writes.  There are two ways to go about it though:

**1. Store all writes in a segment tree, only flush to log on fsync()**

Whenever you do a write, store the metadata and data of the write in a segment tree. On fsync() or memory pressure, write out everything to the log, and clear the tree.

Benefits:

- Easiest to implement
- The log grows slower, since there would be no overlapping writes stored in the log on every fsync().

Downsides:

- The writes are only flattened between fsyncs().  If you write to byte 1, fsynced, then wrote to byte 1 and fsynced again, the log would contain two writes to byte 1.
- Detecting memory pressure would be hard.
- More overhead on a write as you could potentially have to reallocate buffers in the segment tree on overlapping writes.  For example if you wrote to bytes 1-10 and then wrote to 1-5, you would have to reallocate the buffer on the 1-10 write to only hold 6-10.  This could be an issue with huge writes.

**2. Store all writes to the log as we're doing now, flatten write metadata on fsync()**

Write to the log just like we're doing now. On fsync(), re-write the log metadata from our segment tree with the flattened writes.  No actual data in the log is flattened, only metadata.

Benefits:

- Would make sure *all* writes up until that point were flattenened, not just those since last fsync().  We can do this since we're not storing the write data in the tree, only the metadata about the writes (which is tiny).
- Reads would be faster than doing the #1 method, since all the writes would have been flattened, not just the writes between fsyncs().

Downsides:

- The log grows at the same rate as now.  That is, all write data is saved, even if it's been overwritten.  Only the metadata is write flattened.
- Harder to implement

**Comment by MichaelBrim** [comment]
I prefer the second design. As part of the client library work I am doing, I'm hoping we can keep the write log metadata on a per-file basis, rather than the mess we have now where the metadata for all open files is interleaved. I think using segment trees requires us to do this per-file anyway. I have some code that already splits out the write log into an implementation that is shared between client and server sides (i.e., it's part of the common library). We should discuss whether the metadata segment tree code belongs there too.

**Comment by tonyhutter** [comment]
@MichaelBrim right, the segment tree is currently per-file (the tree is stored in `unifyfs_filemeta_t`).

**Comment by tonyhutter** [comment]
I'm planning to implement option 2 unless I hear otherwise.  @adammoody mentioned in an email to me that he'd be in favor of that as well.  He said that he doesn't expect there to be a lot of re-writes, so the extra log size wouldn't be a big deal.

**Comment by tonyhutter** [comment]
#414 implements write flattening.  Closing issue
