### ISSUE TITLE
Corruption while doing many writes to multiple open files

### ISSUE THREAD

**Issue by tonyhutter** [LLNL/UnifyFS#411]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       | Linux
OS Version             | TOSS (modified RHEL 7.5)
Architecture           | x86_64
UnifyFS Version        | dev

### Describe the problem you're observing
While testing out my "flattening writes" code, I decided to write a test case to do a lot of random writes to a bunch of open files and verify the data was correct.  When I ran the test, I noticed what appears to be corrupted data when running the test with 20 open files and ~10k writes.  I don't seem to get the corruption as much or at all if I lower the number of open files to ~10 or so.  Below is the result of 6 runs, with 5 of them showing corruption, and one showing success.   Just looking at the data, it appears the bad writes may be going to the wrong offsets (or they're being read back wrong).  The reproducer is here https://github.com/tonyhutter/UnifyFS/blob/corrupt-data/examples/src/corrupt.c
```
/unifyfs/tmp.q3q1N8X0K8: read 1046736 bytes
/unifyfs/tmp.q3q1N8X0K8 failed at offset 5204 (tmpbuf['I'] != bigbuf['E'])
Comparing last 10 bytes before/after:
expected: UVWXYZABCD|E|FGHIJKLMNO
got:                |I|JKLMNOPQ  
file 7/20 failed


/unifyfs/tmp.iMVbmI3GP4: read 1045839 bytes
/unifyfs/tmp.iMVbmI3GP4 failed at offset 1607 (tmpbuf['I'] != bigbuf['V'])
Comparing last 10 bytes before/after:
expected: LMNOPQRSTU|V|WXYZABCDEF
got:                |I|JKLMNOPQRS
file 1/20 failed


/unifyfs/tmp.yQTL6L7eFT: read 1048150 bytes
/unifyfs/tmp.yQTL6L7eFT failed at offset 834 (tmpbuf['I'] != bigbuf['C'])
Comparing last 10 bytes before/after:
expected: STUVWXYZAB|C|DEFGHIJKLM
got:                |I|JKLMNOPQRS
file 1/20 failed


/unifyfs/tmp.2jweY5gncF: read 1047859 bytes
/unifyfs/tmp.2jweY5gncF failed at offset 2366 (tmpbuf['I'] != bigbuf['A'])
Comparing last 10 bytes before/after:
expected: QRSTUVWXYZ|A|BCDEFGHIJK
got:                |I|JKLMNOPQRS
file 1/20 failed


2019-12-02T17:08:28 tid=159524 @ unifyfs_fd_read() [unifyfs-sysio.c:547] returning EOF
/unifyfs/tmp.Q2IJ42lCVO: read 0 bytes
Passed!
2019-12-02T17:08:28 tid=159524 @ unifyfs_unmount() [unifyfs.c:2555] calling unmount


/unifyfs/tmp.YNoZAef8Bt: read 1048018 bytes
/unifyfs/tmp.YNoZAef8Bt failed at offset 1497 (tmpbuf['C'] != bigbuf['P'])
Comparing last 10 bytes before/after:
expected: FGHIJKLMNO|P|QRSTUVWXYZ
got:                |C|DEFGHIJKLM
file 5/20 failed
```

### Describe how to reproduce the problem
Checkout the branch https://github.com/tonyhutter/UnifyFS/tree/corrupt-data .  Run these commands from inside the workspace:
```
# Build UnifyFS & allocate a node

# Create dir for spillover meta and data (these should be empty)
mkdir ~/meta
mkdir ~/data

# Start the server with all debug prints enabled
./start-server

# Run the reproducer
./start-corrupt
```

**Comment by tonyhutter** [comment]
After further digging, it looks like some of the fsync() calls are failing.  Here's a case where the first file is synced, but the second is not:
```
2019-12-02T18:21:18 tid=11772 @ invoke_client_fsync_rpc() [margo_client.c:417] invoking the fsync rpc function in client
2019-12-02T18:21:18 tid=11772 @ invoke_client_fsync_rpc() [margo_client.c:426] Got response ret=0
2019-12-02T18:21:18 tid=11772 @ unifyfs_intercept_fd() [unifyfs.c:455] Changing fd from exposed 16384 to internal 0
2019-12-02T18:21:18 tid=11772 @ __wrap_close() [unifyfs-sysio.c:2234] closing fd 0
2019-12-02T18:21:18 tid=11772 @ unifyfs_intercept_fd() [unifyfs.c:455] Changing fd from exposed 16384 to internal 0
2019-12-02T18:21:18 tid=11772 @ unifyfs_get_fid_from_path() [unifyfs.c:510] File found: unifyfs_filelist[1].filename = /unifyfs/tmp.KPX0fMRlb6
2019-12-02T18:21:18 tid=11772 @ __wrap_chmod() [unifyfs-sysio.c:2386] chmod: setting /unifyfs/tmp.KPX0fMRlb6 to 444
2019-12-02T18:21:18 tid=11772 @ invoke_client_filesize_rpc() [margo_client.c:379] invoking the filesize rpc function in client
2019-12-02T18:21:18 tid=11772 @ invoke_client_filesize_rpc() [margo_client.c:388] Got response ret=0
2019-12-02T18:21:18 tid=11772 @ unifyfs_set_global_file_meta_from_fid() [unifyfs.c:876] setting fattr to 1035584
2019-12-02T18:21:18 tid=11772 @ invoke_client_metaset_rpc() [margo_client.c:296] invoking the metaset rpc function in client
2019-12-02T18:21:18 tid=11772 @ invoke_client_metaset_rpc() [margo_client.c:305] Got response ret=0
2019-12-02T18:21:18 tid=11772 @ unifyfs_intercept_fd() [unifyfs.c:455] Changing fd from exposed 16385 to internal 1
2019-12-02T18:21:18 tid=11772 @ invoke_client_fsync_rpc() [margo_client.c:417] invoking the fsync rpc function in client
2019-12-02T18:21:18 tid=11772 @ invoke_client_fsync_rpc() [margo_client.c:426] Got response ret=2022
/unifyfs/tmp.31zgPEFwOB 2/10 failed to sync, rc = -1, (errno 2022 Unknown error 2022)
```
I'm looking into it...

**Comment by MichaelBrim** [comment]
@tonyhutter This is a good test case. We should add it to the examples or unit tests.

I wouldn't expect the current code to pass this test because we don't properly handle overlapping writes from the same client. Some failures may also be related to issue #381.

**Comment by tonyhutter** [comment]
Whoops, I should have looked in the server logs earlier.  I'm seeing this on the fsync:
```
2019-12-03T10:35:17 tid=105227 @ unifyfs_set_file_extents() [unifyfs_metadata.c:419] Error inserting file extents into MDHIM
2019-12-03T10:35:17 tid=105227 @ rm_cmd_fsync() [unifyfs_request_manager.c:880] unifyfs_set_file_extents() failed
```

**Comment by tonyhutter** [comment]
Figured it out.  `mdhimBPut()` fails when the number of entries is zero, which is what I was seeing sometimes (an fsync() with no extents to sync).  This fixes it:

```C
int rm_cmd_fsync(int app_id, int client_side_id, int gfid)
{

...

+    if (extent_num_entries == 0) {
+        /* Nothing to do */
+        return UNIFYFS_SUCCESS;
+    }
```
I'll add this fix to my write-flattening code, along with the new test case.

**Comment by MichaelBrim** [comment]
@tonyhutter Is there any way we can check this condition on the client side and not actually do a no-op fsync rpc?

**Comment by tonyhutter** [comment]
Yes, the `rm_cmd_fsync()` change is on the client side.

**Comment by tonyhutter** [comment]
Unfortunately, running with the fsync fix, I still get corruption when I crank up the number of files...:
```
2019-12-03T11:34:22 tid=109055 @ delegator_signal() [unifyfs-sysio.c:1616] receive buffer now empty
/unifyfs/tmp.pCLfAYj42f: read 1046425 bytes
/unifyfs/tmp.pCLfAYj42f failed at offset 6631 (tmpbuf['S'] != bigbuf['B'])
Comparing last 10 bytes before/after:
expected: RSTUVWXYZA|B|CDEFGHIJKL
got:                |S|T         
file 3/30 failed
```

**Comment by MichaelBrim** [comment]
@tonyhutter just to be perfectly clear, `rm_cmd_fsync()` is a server-side function. Is the check added to that function?

**Comment by tonyhutter** [comment]
You're right, my mistake!  I think we could add the check to `invoke_client_fsync_rpc()` if we want to do it on the client side.

**Comment by adammoody** [comment]
I see all of your reads are returning a full 1MB ```read 1048150 bytes```, even though you are randomly writing different amounts at different offsets.  Note that a file shorter than 1MB will still return 1MB on read() due to https://github.com/LLNL/UnifyFS/issues/368.

Do you expect all of the files to be at least 1MB long?

**Comment by adammoody** [comment]
Oh wait, on second glance I see those numbers above are actually different.  Nevermind.

**Comment by adammoody** [comment]
@tonyhutter , can you verify that this is resolved?

**Comment by tonyhutter** [comment]
> @tonyhutter , can you verify that this is resolved?

@adammoody yes and no.  And the 'no' may be a totally different issue.  What I'm seeing is that if I use `NUM_FILES=20` in `corrupt.c` it works fine, and does fix the corruption.  However, if I set `NUM_FILES=30`, I see cases where when I read() the entire file, it reports back 0 bytes read:
```

/unifyfs/tmp.5CpcveI7Pz: read 0 bytes, fd=16413
/unifyfs/tmp.JHHu02V23z: read 1047038 bytes, fd=16412
/unifyfs/tmp.luUHtrFe83: read 0 bytes, fd=16411
/unifyfs/tmp.2m2ZqW6I4X: read 1048121 bytes, fd=16410
/unifyfs/tmp.rRbnOsgBtv: read 1046007 bytes, fd=16409
/unifyfs/tmp.QJ1JylRQq8: read 1047873 bytes, fd=16408
/unifyfs/tmp.Hz7kOyBeGN: read 1044491 bytes, fd=16407
/unifyfs/tmp.mHNr153oWu: read 0 bytes, fd=16406
/unifyfs/tmp.xpagQmJlgp: read 0 bytes, fd=16405
/unifyfs/tmp.9zcD3kKQd7: read 0 bytes, fd=16404
/unifyfs/tmp.PFRczbTgXP: read 1044434 bytes, fd=16403
/unifyfs/tmp.24xsgT87Ux: read 0 bytes, fd=16402
/unifyfs/tmp.LzsjYoEc2P: read 1047555 bytes, fd=16401
/unifyfs/tmp.q4UFtY3oVN: read 0 bytes, fd=16400
...
```
I know via printfs that I added that the files actually are being written.  For example, we can see that fd 16406 had four writes done to it, but a read() of the file returns 0:
https://gist.github.com/tonyhutter/91db4395698c26fb6e2e89ad04131209

My added debug prints to corrupt.c have been pushed them to my `tonyhutter:corrupt-data` branch.  Here's the direct link to the new corrupt.c: https://github.com/tonyhutter/UnifyFS/blob/corrupt-data/examples/src/corrupt.c

**Comment by adammoody** [comment]
I could see the same thing when testing now.  I tracked my failures down to the filesize being reported as 0 for a set of files.  Thinking that was curious, I added some error checking around the write() call in corrupt.c:
```
        errno = 0;
        ssize_t nwrite = write(fd, &bigbuf[start], count);
        if (nwrite == -1) {
            printf("write %d to file %d failed %s\n", i+1, rnd, strerror(errno));
        }
```
With that, I can see that the test case exhausts the space for me:
```
write 34 to file 23 failed No space left on device
write 35 to file 15 failed No space left on device
```
Are you also maybe running out of space?

**Comment by adammoody** [comment]
Note that using more files will use up more space, even with the same number of writes, because of how we allocate blocks.

**Comment by tonyhutter** [comment]
@adammoody yep, I'm getting ENOSPC.  Thanks for tracking that down.  I think we're good then, closing this issue.
