### ISSUE TITLE
Make gfid calculation endian independent

### ISSUE THREAD

**Issue by tonyhutter** [LLNL/UnifyFS#461]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       | all
OS Version             | all
Architecture           | all
UnifyFS Version        | all

### Describe the problem you're observing
We currently calculate a gfid like this:
```C
int unifyfs_generate_gfid(const char* path)
{
    unsigned char digested[16] = { 0, };
    unsigned long len = strlen(path);
    int* ival = (int*) digested;

    MD5((const unsigned char*) path, len, digested);

    return abs(ival[0]);
}
```
We basically hash our path into a 16-byte value, and cast the first four bytes to be the gfid.  This is a problem since you're going to get a different gfid based on if you're running a little or big endien nodes.  For example, if `digested[] = {0x00, 0x11, 0x22, 0x33, ...}` then `*ival` would be:

big endian: 0x00112233
little endian: 0x33221100

We should change it to be endian independent:
```C
unsigned int ival = (digested[0] << 24) | (digested[1] << 16) | (digested[2] << 8) | digested[3];
```
The only problem is that if we're storing the gfid in the filesystem metadata, then making this change would corrupt all little endian Unify filesystems.

We will need to make this change if we ever plan to cross mount Unify filesystems across big/little endian nodes (or servers).

**Comment by MichaelBrim** [comment]
@tonyhutter I agree that the current method is unsafe across varying endianess. To date, this has never been a problem because we only exist in the context of a single job, and no currently deployed HPC systems have nodes with different endianess mixed within a job.

**Comment by MichaelBrim** [comment]
We should discuss this on the concall. If people want to make the change. I can go ahead an do what you suggested.

**Comment by MichaelBrim** [comment]
This was fixed a while back, closing.
