### ISSUE TITLE
The --enable-mpi-mount configure option breaks the build

### ISSUE THREAD

**Issue by CamStan** [LLNL/UnifyFS#467]
Building with the `--enable-mpi-mount` configure option currently breaks the build.

An open Spack issue originally reported this problem ([#15292](https://github.com/spack/spack/issues/15292)) and has a log of the attempted build. I was able to track it down and confirm that it was at least the configure option causing it, but haven't dug into why yet.

Current workaround is to not use the option, or when building with Spack, to do:
```
spack install unifyfs~auto-mount
```
@MichaelBrim

**Comment by MichaelBrim** [comment]
@CamStan Looks like we're not #including mpi.h in the pmpi_wrappers.h file. I don't remember if this was intentional. Can you try just moving the `#include <mpi.h>` from pmpi_wrappers.c to pmpi_wrappers.h?

**Comment by CamStan** [comment]
That seems to have fixed it. Thanks @MichaelBrim!

I'll submit a PR.
