### ISSUE TITLE
Problems with setting of log verbosity

### ISSUE THREAD

**Issue by clmendes** [LLNL/UnifyFS#495]
As suggested by @kathrynmohror and @adammoody I am creating
this issue to report problems observed when setting log verbosity
via environment variables in my Catalyst job script.

So far, I had been using UNIFYFS_LOG_LEVEL with my old Unify
version. However, now, after cloning the current 'dev' version (Apr.29),
I read in the documentation page about UNIFYFS_LOG_VERBOSITY.

By using the same test-case of issue #488 addressing the file-rewrite
problem, I did several executions on Catalyst where I set varying
values for UNIFYFS_LOG_VERBOSITY in each. Then, I verified the
size of the stderr file and the size of the server log for each
execution of this program:

UNIFYFS_LOG_VERBOSITY=0 - stderr size = 0    (server log: 15028)
UNIFYFS_LOG_VERBOSITY=1 - stderr size = 0    (server log: 15028)
UNIFYFS_LOG_VERBOSITY=2 - stderr size = 311  (server log: 15028)
UNIFYFS_LOG_VERBOSITY=3 - stderr size = 311  (server log: 15028)
UNIFYFS_LOG_VERBOSITY=4 - stderr size = 311  (server log: 15028)
UNIFYFS_LOG_VERBOSITY=5 - stderr size = 3872 (server log: 15028)
UNIFYFS_LOG_VERBOSITY=6 - stderr size = 311 (server log:  15028)

For *all* these cases, the server log (in $jobdir/logs/...) shows:

UNIFYFS CONFIG: log.verbosity = 5

Next, I repeated these executions varying UNIFYFS_LOG_LEVEL, which
I was using so far with previous Unify versions. The behavior
in all cases was the same as with UNIFYFS_LOG_VERBOSITY=0.

Thus, my three questions would be:

a) Is UNIFYFS_LOG_LEVEL indeed no longer valid?

b) By using UNIFYFS_LOG_VERBOSITY, why is the server log size
always the same? Why does it always show 'log.verbosity = 5'?

c) Shouldn't the case of UNIFYFS_LOG_VERBOSITY=6 be flagged
as an error? (documentation says its values are [0-5])

**Comment by MichaelBrim** [comment]
a) I can't easily view the whole history here due to the name change from UnifyCR to UnifyFS, but I believe UNIFYFS_LOG_LEVEL became UNIFYFS_LOG_VERBOSITY back when I introduced configurator a long, long time ago. 

b) The reason the server setting is always 5 is due to starting the servers with the `unifyfs` command-line utility, which sets that level for the servers if you pass it the debug flag `-d`.

c) A setting of 6 is out of range and thus ignored by `unifyfs_set_log_level` (common/src/unifyfs_log.c). We could easily print a warning to stderr in this case.

**Comment by clmendes** [comment]
Thanks @MichaelBrim for the information.

In my jobs, I have been starting the server with

  ./unifyfs start --share-dir=$mydir  -d -c -e  $mydir/unifyfsd &

but this is a setting from my very early tests, and I've never changed it. So, I'll try to remove the "-d" and let the debugging level to be set only by the env-var UNIFYFS_LOG_VERBOSITY in the job script. I will do some tests and report here.

**Comment by clmendes** [comment]
@MichaelBrim , I tested this today, with the fresh Unify version that I had cloned from 'dev' a week ago, and it does indeed work fine with UNIFYFS_LOG_VERBOSITY:

* if it's set to 5, I get full details in the client log;
* if it's set to 0, the client log files remain emply;
* if it's not set, the client log files remain empty, as expected (default=0)

For these tests, I did NOT use the '-d' flag when starting the server, and then the server log also behaves as indicated by  UNIFYFS_LOG_VERBOSITY.

Thus, I believe this issue can be closed.
