### ISSUE TITLE
spack fails during CI build

### ISSUE THREAD

**Issue by MichaelBrim** [LLNL/UnifyFS#501]
Not sure why spack fails during CI build:

```
before_install.1
4610.00s$ test -n $CC && unset CC
before_install.2
46212.42s$ (cd $HOME/spack; git describe) || git clone https://github.com/spack/spack $HOME/spack
before_install.3
4710.00s$ test -f $HOME/spack/etc/spack/packages.yaml || cat > $HOME/spack/etc/spack/packages.yaml << '  EOF'
4970.53s$ $HOME/spack/bin/spack bootstrap
498==> Error: bootstrap is not a recognized Spack command or extension command; check with `spack commands`.
499The command "$HOME/spack/bin/spack bootstrap" failed and exited with 1 during .
```

_Originally posted by @sandrain in https://github.com/LLNL/UnifyFS/pull/500#issuecomment-627985739_

**Comment by MichaelBrim** [comment]
I believe 'spack bootstrap' has been removed from the latest spack master, because it is no longer required.

**Comment by CamStan** [comment]
> I believe 'spack bootstrap' has been removed from the latest spack master, because it is no longer required.

Looks like that is correct ([related PR is Spack](https://github.com/spack/spack/pull/15179)).
Just got this working on my fork, so I'll submit a PR.

Spack has changed how `spack load` works, and it no longer uses the underlying Spack-generated module files. So, after removing `spack bootstrap` from our .travis.yml, this ran into another issue as the module command was no longer available: 
```
source <(spack module tcl loads leveldb gotcha@0.0.2 flatcc mercury argobots margo)
module: command not found
The command "source <(spack module tcl loads leveldb gotcha@0.0.2 flatcc mercury argobots margo)" failed and exited with 127 during .
```

Fixed this by just doing `spack load` after each `spack install`:
```
spack install leveldb && spack load leveldb
```
