### ISSUE TITLE
astyle makes a mess of .t tests

### ISSUE THREAD

**Issue by craigsteffen** [LLNL/UnifyFS#520]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       |
OS Version             |
Architecture           |
UnifyFS Version        |

### Describe the problem you're observing
astyle when run on .t test source script files makes a mess.  It added inappropriate spaces, and in some cases splits apart path names and inserts spaces into them

It also removes x permmissions files it runs on.  

### Describe how to reproduce the problem

run astyle --options=scripts/unifyfs.astyle ./t/XXXX-some-test.t

**Comment by craigsteffen** [comment]
I may have been wrong about half of this.  It may not actually remove execute permissions.  It does scramble the contents, though.

**Comment by MichaelBrim** [comment]
@craigsteffen astyle is intended for use on C source code files, not bash scripts or anything else.
