### ISSUE TITLE
Failure exporting data file created in unifyfs by multi-node execution

### ISSUE THREAD

**Issue by clmendes** [LLNL/UnifyFS#525]
@adammoody and @MichaelBrim ,

As I had reported in our latest call, I'm having trouble exporting the datafile that is produced under /unifyfs in a multi-node execution on Catalyst of an MPI program. This error also happens, for example, when I run the example at /examples/src/app-mpiio.c and try to export file testfile using sysio-cp-gotcha: this copy utility hangs, and the exported file is left incomplete.

Logs from the client and from the server show that the client was expecting to read more data, whereas the server on that same node was waiting for work. Thus, it looks like a deadlock scenario.

This problem occurs even running with just two nodes, and one processor per node. I reproduced the problem with the code below, which simply tries to create a 64-byte file using function MPI_File_write_at. This works fine with multiple processors on a single node, but running with two processors on two nodes (i.e. one processor per node) results in a file test.dat that cannot be exported by sysio-cp-gotcha.

Note: the ufs:/unifyfs naming is used such that we can run with Mvapich, according to the hint received from Rob Latham.

Example program:

#define FILESIZE 64
#include <stdio.h>
#include "mpi.h"
#include <unifyfs.h>
int main(int argc, char *argv[])
{
        int ret=0;
        MPI_File fh;
        MPI_Status status;
        MPI_Offset offset;
        int buf [FILESIZE/sizeof(int)], rank, nprocs, nints, count, i;
        MPI_Init (0,0);
        MPI_Comm_rank (MPI_COMM_WORLD, &rank);
        MPI_Comm_size (MPI_COMM_WORLD, &nprocs);
        ret = unifyfs_mount("/unifyfs", rank, nprocs, 0);
        if (ret) {
                fprintf(stderr,"unifyfs_mount failed, rank %d (return = %d)\n",rank,ret);
                exit(-1);
        }
        for (i=0; i<FILESIZE/sizeof(int); i++) buf[i]=rank;
        nints = FILESIZE/(nprocs*sizeof(int));
        offset = rank * nints * sizeof(int);
        /* OPen File collectively */
        MPI_File_open(MPI_COMM_WORLD, "ufs:/unifyfs/test.dat",
                MPI_MODE_CREATE|MPI_MODE_RDWR, MPI_INFO_NULL, &fh);
        if (fh==NULL) fprintf(stderr,"[%d] MPI_File_open ERROR\n",rank);
        /* Write to File */
        MPI_File_write_at(fh, offset, buf, nints, MPI_INT, &status);
        /* Report amount written */
        MPI_Get_count(&status, MPI_INT, &count);
        printf("[%d] : count %d, offset %d, nints %d, buf[0]=%d\n",rank,count,offset,nints,buf[0]);
        /* Close File collectively */
        MPI_File_close(&fh);
        MPI_Finalize();
}

**Comment by MichaelBrim** [comment]
@clmendes Where is the call to `unifyfs_unmount()` in this example?

**Comment by clmendes** [comment]
@MichaelBrim  ,

I don't really have a unifyfs_unmount call. Is it mandatory?  The sysio-cp-gotcha utility is run subsequently in the same job.

Like I said, this example works fine with P=2 or P=4 in the same node, and then export the file via sysio-cp-gotcha.

**Comment by MichaelBrim** [comment]
If you call unifyfs_mount(), you should call unifyfs_unmount(). The only time you don't call unifyfs_mount() is when Unify is configured to use PMPI wrappers to call mount/unmount at MPI_Init/Finalize().

**Comment by clmendes** [comment]
@MichaelBrim ,

OK, I just added unifyfs_unmount after closing the file with MPI_File_close, but it doesn't change the behavior. In the log of the client, when running the example, I now see

2020-06-22T12:25:53 tid=48963 @ unifyfs_unmount() [unifyfs.c:2576] calling unmount

in two places (i.e.both ranks are calling it), but then, when running sysio-cp-gotcha I still have the same deadlock, i.e. it's aborted when the job time ends.

**Comment by adammoody** [comment]
@clmendes , does this also hang for you on quartz?

I tried on quartz and lassen, and it's working for me in both cases.  I'll try catalyst now.

To be sure, I'm running the job in the same way, can you list the command you're using to run the job that writes the file?

Also the command you are running to copy the file out?

**Comment by adammoody** [comment]
@clmendes , when pasting code into an issue like this, it helps to add three consecutive ` characters before and after the code segment.  This tells github to print the text verbatim instead of trying to format it.  For example, you can see the code example in your description at the top of the issue has been modified from your original code.  I was able to put that back together, but this will help for future posts.

**Comment by adammoody** [comment]
Hit a corner case that took a while to debug.  Since I like to run under totalview, I still prefer to launch the servers by hand.  That looks something like this hacky thing:
```
procs=$SLURM_NNODES
srun -n $procs -N $procs touch /var/tmp/unifyfs.conf
srun -n $procs -N $procs mkdir /dev/shm/unifyfs

export UNIFYFS_CONFIGFILE=/var/tmp/unifyfs.conf
export UNIFYFS_SERVER_LOCAL_EXTENTS=0
export UNIFYFS_SHAREDFS_DIR=/p/lustre2/user1
export UNIFYFS_DAEMONIZE=off

totalview srun -a -n $procs -N $procs `pwd`/bin/unifyfsd
```
However, in this case, I apparently built without PMI or PMI2 support, and I had forgotten to create a servers hostfile.  In that situation each server initializes ```glb_pmi_rank = 0``` and ```glb_pmi_size = 1```.  During the run, each server thinks it is server rank 0, and so it generates key/value pairs using that information.

Then a ran a job with two nodes, one server per node, and one client per node.  Each client wrote one extent, and the extents do not overlap.  Each server inserted one key/value pair into MDHIM while both assumed they were server rank=0.  When reading the data back out, a server ends up reading back both keys from MDHIM successfully, but then it thinks both extents are local, since the delegator_rank=0 in both key/value pairs.  This resulted in a file that was the correct size, but the read returned "corrupted" data.

Not sure what to do about it yet, but I wanted to document the case to capture the details.

**Comment by adammoody** [comment]
@clmendes , things seem to be working for me on catalyst, too, though I did make one patch that may or may not be related.  Anyway, I think I'll need more info from you in order to reproduce what you're seeing.

**Comment by sandrain** [comment]
@clmendes Could you check if #529 fixes this?

**Comment by clmendes** [comment]
@sandrain  I tested this today, using the branch from #529 but it still fails for me.

@adam , I tested it today with the same example that I reported in this issue. My dir for today's test was /g/g12/mendes3/MPI/UN-MPIIO/TEST-OAK  and my new Unify  build, from Hyogi's branch, is located at /g/g12/mendes3/UnifyFS-Oak/  

The behavior is the same: file test.dat ends up with zero bytes, and the server log shows that the server is waiting for work.

**Comment by sandrain** [comment]
@clmendes There should be other things going on. In my test (without mpiio), `sysio-cp` now works. It became unresponsive before the fix.

**Comment by adammoody** [comment]
@clmendes , thanks.  I can reproduce with your job, so I'm debugging now.  I did find that it completes successfully at times under a debugger.  I also noticed that your build is optimized where as I had been using a full debug build.  So it feels like a race condition is also in play.

**Comment by clmendes** [comment]
@sandrain  and @adammoody , thanks for the updates. Yes, I agree that there should be other things going on.

Today, I did more tests on Catalyst with another program from Ron Latham's ROMIO tests, perf.c, posted at https://raw.githubusercontent.com/pmodels/mpich/master/src/mpi/romio/test/perf.c

This program produces a single (shared) file with size 4MB/rank. I'm running it with 2 nodes and 2 ranks/node, thus it will produce a 16MB file. I'm exporting it out of /unifyfs with the --stage-out option at 'terminate'. With my previous build of Unify, it hangs when the file is at around 9MB (I saw that unifyfs-stage does the transfer in chunks of 1MB). However, using Hyogi's new branch , the transfer does work fine, and the file ends up complete!

Thus, I see that Hyogi's branch indeed improves the situation. But I could not yet get it to work with the example that I had originally posted here, which produces a small shared file (size=64 bytes) as had been suggested by Adam.

I'll repost the code for this example here, this time hopefully with the correct formatting.

**Comment by clmendes** [comment]
Reposting the original test code:

```
#define FILESIZE 64
#include <stdio.h>
#include "mpi.h"
#include <unifyfs.h>
int main(int argc, char *argv[])
{
        int ret=0;
        MPI_File fh;
        MPI_Status status;
        MPI_Offset offset;
        int buf [FILESIZE/sizeof(int)], rank, nprocs, nints, count, i;
        MPI_Init (0,0);
        MPI_Comm_rank (MPI_COMM_WORLD, &rank);
        MPI_Comm_size (MPI_COMM_WORLD, &nprocs);
        ret = unifyfs_mount("/unifyfs", rank, nprocs, 0);
        if (ret) {
                fprintf(stderr,"unifyfs_mount failed, rank %d (return = %d)\n",rank,ret);
                exit(-1);
        }
        for (i=0; i<FILESIZE/sizeof(int); i++) buf[i]=rank;
        nints = FILESIZE/(nprocs*sizeof(int));
        offset = rank * nints * sizeof(int);
        /* OPen File collectively */
        MPI_File_open(MPI_COMM_WORLD, "ufs:/unifyfs/test.dat",
                MPI_MODE_CREATE|MPI_MODE_RDWR, MPI_INFO_NULL, &fh);
        if (fh==NULL) fprintf(stderr,"[%d] MPI_File_open ERROR\n",rank);
        /* Write to File */
        MPI_File_write_at(fh, offset, buf, nints, MPI_INT, &status);
        /* Report amount written */
        MPI_Get_count(&status, MPI_INT, &count);
        printf("[%d] : count %d, offset %d, nints %d, buf[0]=%d\n",rank,count,offset,nints,buf[0]);
        /* Close File collectively */
        MPI_File_close(&fh);
/*      unifyfs_unmount();  */
        MPI_Finalize();
}
```

**Comment by sandrain** [comment]
@clmendes I have just tested your test code with FILESIZE set to 64B and 64MB. Both cases ran fine with 4 nodes (ppn=1) on summitdev:

1. mpitest code (@clmendes 's code)
2. `sysio-stat-static /unifyfs/test.dat`
3. `sysio-cp-static /unifyfs/test.dat /gpfs/somewhere/test.dat`

Maybe, this is something to do with the mpi io lib in Catalyst? I also remember @MichaelBrim said mpi io test (our example code) ran fine on summitdev with his recent PR.

**Comment by adammoody** [comment]
> 
> 
> @sandrain I tested this today, using the branch from #529 but it still fails for me.
> 
> @adam , I tested it today with the same example that I reported in this issue. My dir for today's test was /g/g12/mendes3/MPI/UN-MPIIO/TEST-OAK and my new Unify build, from Hyogi's branch, is located at /g/g12/mendes3/UnifyFS-Oak/
> 
> The behavior is the same: file test.dat ends up with zero bytes, and the server log shows that the server is waiting for work.

@clmendes , are you sure you pulled @sandrain 's fix?

The test problem I am running from /g/g12/mendes3/MPI/UN-MPIIO/TEST-OAK in job.Oak seems to be using the old code before the fix.  I think it gets caught on the same bug.

**Comment by clmendes** [comment]
@adammoody , my Unify version that is being used by job.Oak was obtained as follows: I navigated to https://github.com/sandrain/UnifyFS/tree/rm-remote-request-fix  and then, once there, I followed what was in the green "Clone" tab, which was containing "https://github.com/sandrain/UnifyFS.git" 

Thus, on Catalyst, I simply did 

git clone https://github.com/sandrain/UnifyFS.git

and then proceeded with the Unify build as usual. Is this wrong?

**Comment by sandrain** [comment]
@clmendes I think that will pull the current dev branch. Try:

```
$ git clone https://github.com/sandrain/UnifyFS.git
$ cd UnifyFS
$ git checkout rm-remote-request-fix
```
You can check `git branch` to see if you are in the right branch.

**Comment by clmendes** [comment]
@adammoody , @sandrain :  Yes, I indeed had the old version (without the fix).

I got it now, and tested with this program. It does work fine for me now! I will try next to test the ROMIO example and the app-mpiio.c from the Unify distribution. I'll let you know how it goes.

Thanks!

**Comment by clmendes** [comment]
@sandrain , @adammoody , I tested today two of the codes from Rob's ROMIO test set, running with 4 nodes on Quartz based on this Unify version built from Hyogi's branch, and they both worked fine. The produced files were retrieved fine (via --stage-out), and their contents match the same that is produced when running without Unify.

Thus, I think we can close this issue.
