### ISSUE TITLE
unifyfs_mount_prefix being free'd by config processing

### ISSUE THREAD

**Issue by adammoody** [LLNL/UnifyFS#526]
@MichaelBrim , while trying to debug @clmendes 's hang, I came across an unrelated bug that I wanted to run by you for your suggestion.  So in ```uniyfs_mount()```, we strdup the prefix that the user passes in:
https://github.com/LLNL/UnifyFS/blob/4e8092f5d89f4456780ea3952184788170162621/client/src/unifyfs.c#L2525
We then copy the pointer to that string and attach it to the config structure here:
https://github.com/LLNL/UnifyFS/blob/4e8092f5d89f4456780ea3952184788170162621/client/src/unifyfs.c#L2527
However, in my test case, the string in ```client_cfg.unifyfs_mountpoint``` gets freed and replaced while processing the config values in the runstate file from the call here:
https://github.com/LLNL/UnifyFS/blob/4e8092f5d89f4456780ea3952184788170162621/client/src/unifyfs.c#L2537
The problem I'm seeing is that we continue to reference the ```unifyfs_mount_prefix``` global variable, but that variable now points to invalid memory.  The pointer that was copied to the config struct was free'd in the call to read_runstate.

Should we be setting ```unifyfs_mount_prefix``` after processing the runstate?

Or should we be attaching a strdup of unifyfs_mount_prefix to the structure?

**Comment by MichaelBrim** [comment]
Reading the runstate should come second, as it is meant as an update to client config based on things under the server's control. However, this really points to a bug in the fact that client's provided mountpoint should always be used. We should remove the mountpoint from the runstate file to prevent such a server override.

**Comment by MichaelBrim** [comment]
@adammoody The more I think about this, the more convinced I am that the runstate file is not useful. All of the configuration options that are relevant to the client should be set by the client. I can't come up with a single example where the server should override a client setting. Can you think of any?

**Comment by adammoody** [comment]
I'm fine with that.  I don't have a solid enough grasp of everything being set in the client through that file to know offhand.  We could bring this up on the next call to see if others can think of anything.

**Comment by MichaelBrim** [comment]
closing due to fix in #535
