### ISSUE TITLE
Testing: chdir() relative path tests failing on CI systems

### ISSUE THREAD

**Issue by CamStan** [LLNL/UnifyFS#533]
### Describe the problem you're observing
Both the `static` and `gotcha` version of our `chdir()` unit tests specific to relative paths are failing on both x86_64 and Power9 systems that our CI tests run on, with one additional test failing on the x86_64 system.

Tests using `getcwd()` and `get_current_dir_name()` are showing the failures when being called after previous `chdir()` calls.

### Describe how to reproduce the problem
After building UnifyFS on the desired system and assuming this build was done in a separate build/ directory, navigate to the t/ directory and run the tests:
``` 
$ cd build/t
$ make check
```
Can also just run one or both of individual test suites that are failing:
```
$ cd build/t
$ make check TESTS=‘0001-setup.t 0100-sysio-gotcha.t 0500-sysio-static.t 9010-stop-unifyfsd.t 9999-cleanup.t’
```

### Include any warning or errors or releveant debugging data
On both systems, both `static` and `gotcha` versions of these tests are failing:
```
FAIL: 0100-sysio-gotcha.t 338 - ../../t/sys/chdir.c:157 getcwd returned /var/tmp/tmp.Bwm1H1jZE4/mount/dir1/.. expected /var/tmp/tmp.Bwm1H1jZE4/mount
⋮
FAIL: 0100-sysio-gotcha.t 341 - ../../t/sys/chdir.c:170 getcwd returned /var/tmp/tmp.Bwm1H1jZE4/mount/dir1/../dir1 expected /var/tmp/tmp.Bwm1H1jZE4/mount/dir1
⋮
FAIL: 0100-sysio-gotcha.t 344 - ../../t/sys/chdir.c:183 getcwd returned /var/tmp/tmp.Bwm1H1jZE4/mount/dir1/../dir1/././.././dir2 expected /var/tmp/tmp.Bwm1H1jZE4/mount/dir2
⋮
FAIL: 0100-sysio-gotcha.t 356 - ../../t/sys/chdir.c:302 get_current_dir_name returned /var/tmp/tmp.Bwm1H1jZE4/mount/dir1/.. expected /var/tmp/tmp.Bwm1H1jZE4/mount
⋮
FAIL: 0100-sysio-gotcha.t 359 - ../../t/sys/chdir.c:318 get_current_dir_name returned /var/tmp/tmp.Bwm1H1jZE4/mount/dir1/../dir2 expected /var/tmp/tmp.Bwm1H1jZE4/mount/dir2
```
Additionally, on the x86_64 system, this test is also failing:
```
FAIL: 0100-sysio-gotcha.t 343 - ../../t/sys/chdir.c:180 getcwd: Numerical result out of range
```

**Comment by CamStan** [comment]
**Note:** Gitlab CI also runs these tests as me in my environment, so it's not different than me just running them myself. Might be meaningful if others are unable to replicate.

**Comment by adammoody** [comment]
Thanks @CamStan .  That looks like the case when spath is not being used.  Can you tell whether its failed to find spath during the configure?

**Comment by CamStan** [comment]
Ah, yup. Neglected to put spath in the CI testing environment. I'll fix that. Thank you @adammoody

**Comment by CamStan** [comment]
@adammoody, do we, or will we, need mpi support enabled for spath?

**Comment by adammoody** [comment]
No, we don't need MPI support for spath.

**Comment by CamStan** [comment]
That fixed it. Closing this.
