### ISSUE TITLE
unifyfs_sync questions

### ISSUE THREAD

**Issue by adammoody** [LLNL/UnifyFS#570]
While testing the new sync-after-every-write option, I was tracing through the unifyfs_sync code.  A couple of questions:

I think it's possible for a user to have a file open with multiple descriptors, so there could be multiple fd slots that all share the same fid value.  Since ``unifyfs_sync(fid)`` is passed a file id, rather than a file descriptor, I think we should have it look for and flush all file descriptors that match on fid, instead of just the first entry.

https://github.com/LLNL/UnifyFS/blob/968c50dd6d377771994a2ca04a1516af62822dc7/client/src/unifyfs-fixed.c#L215-L218

Is that true?

Also, if data needs to be synced to the spillover file, we should do that *before* we call the server sync rpc.  Otherwise, I think we have a race condition where the server might try to read from the spillover file before the sync to the spill has completed.  I think we should move this code before we call the server rpc.

https://github.com/LLNL/UnifyFS/blob/968c50dd6d377771994a2ca04a1516af62822dc7/client/src/unifyfs-fixed.c#L221-L229

**Comment by adammoody** [comment]
@MichaelBrim , I could look to submit a fix for these if needed, but wanted to make sure if this is right before I bother.

**Comment by adammoody** [comment]
Oh, maybe it's ok to break the loop early after all, since I think we will just have one meta data structure for a given fid.  If that's right, I'll just add a comment about that so that I don't get confused again.

**Comment by MichaelBrim** [comment]
@adammoody Your changes in PR #571 look ok to me.
