### ISSUE TITLE
Error in HDF5-testsuite´s cchunk5 with latest tree-based Unify

### ISSUE THREAD

**Issue by clmendes** [LLNL/UnifyFS#580]
@adammoody , @kathrynmohror : I am creating this new issue to report/document the problem that I'm facing in one of the HDF5 tests (cchunk5), after switching to use the new Unify version based on PR#578, which implemented the new tree-based functionality.

I reproduced the problem with an isolated code that only calls cchunk5, so this is much simpler to handle. I get the same error in this code as in the original HDF5 testsuite. I can share this reproducer if there is interest.

First, a few comments. This problem does NOT occur when I use Unify with the previous "new-margotree" branch. Second, the test works fine when I run it on 1 node (it must be run with 4 processors). When I run it on 2 nodes (i.e. 2 processors/node), even using the new UNIFYFS_CLIENT_WRITE_SYNC=1 setting, and adding a " sleep 25" after starting the server, I get the following error in the application, for the first two ranks:

```
Proc 1: *** Parallel ERROR ***
    VRFY (dataset created succeeded) failed at line  166 in t_chunk.c
Proc 0: *** Parallel ERROR ***
    VRFY (dataset created succeeded) failed at line  166 in t_chunk.c
``` 
This is the section of the source code t_chunk.c where this error happens:

```
164:  dataset = H5Dcreate2(file, DSET_COLLECTIVE_CHUNK_NAME, H5T_NATIVE_INT,
165:                       file_dataspace, H5P_DEFAULT, crp_plist, H5P_DEFAULT);
166:  VRFY((dataset >= 0),"dataset created succeeded");
```

According to my non-Unify execution of this program with Recorder, this H5Dcreate2 function executes the following operations in the four ranks:
```
Rank=0:
0.067066 0.067068 0 lseek ( 15 3688 0 )
0.067073 0.067717 0 read ( 15 0x2055ff0 384 )
0.067736 0.067739 0 lseek ( 15 3688 0 )
0.068010 0.068016 0 write ( 15 0x2055ff0 384 )

Rank=1:
0.067129 0.067132 0 lseek ( 13 4072 0 )
0.067137 0.067831 0 read ( 13 0x2aaacdf670a0 384 )
0.067843 0.067847 0 lseek ( 13 4072 0 )
0.068711 0.068724 0 write ( 13 0x2aaacdf670a0 384 )

Rank=2:
0.088103 0.088105 0 lseek ( 15 4456 0 )
0.088110 0.089104 0 read ( 15 0x205aa70 384 )
0.089119 0.089122 0 lseek ( 15 4456 0 )
0.089802 0.089813 0 write ( 15 0x205aa70 384 )

Rank=3:
0.088163 0.088166 0 lseek ( 13 4840 0 )
0.088173 0.089195 0 read ( 13 0x2aaacdf670a0 384 )
0.089213 0.089216 0 lseek ( 13 4840 0 )
0.089839 0.090577 0 write ( 13 0x2aaacdf670a0 384 )
```

For this execution with the latest Unify version, and 4 processors / 2 nodes, I see the following in the client logs:

```
tid=113413 @ unifyfs_gfid_read_reqs() [unifyfs.c:1097] read: offset:3688, len:384
tid=113414 @ unifyfs_gfid_read_reqs() [unifyfs.c:1097] read: offset:4072, len:384
tid=160537 @ unifyfs_gfid_read_reqs() [unifyfs.c:1097] read: offset:4456, len:384
tid=160538 @ unifyfs_gfid_read_reqs() [unifyfs.c:1097] read: offset:4840, len:384
. . .
tid=113413 @ invoke_client_read_rpc() [margo_client.c:716] Got response ret=1004
tid=113414 @ invoke_client_read_rpc() [margo_client.c:716] Got response ret=1004
tid=160537 @ invoke_client_read_rpc() [margo_client.c:716] Got response ret=61
tid=160538 @ invoke_client_read_rpc() [margo_client.c:716] Got response ret=61
tid=113414 @ unifyfs_gfid_read_reqs() [unifyfs.c:1107] Failed to issue read RPC to server
tid=113413 @ unifyfs_gfid_read_reqs() [unifyfs.c:1107] Failed to issue read RPC to server
```
Thus, we see that Ranks 0 and 1 got trouble reading from the server! This is consistent with the error message reported by the application (Processors 0 and 1), and it did NOT happen when I was using the new-margotree branch. In that case, the four clients received "ret=61", and none failed to issue read RPC to server.

@MichaelBrim had said the following regarding the differences between this current version and that new-margotree branch: 
```
The main difference between new-margotree and dev is that only one server (the "owner") maintains a given file's full metadata until it is laminated, at which time the metadata is broadcast to the other servers. ...  What is relevant is the owner server, which is calculated as (gfid % #servers). In a lot of cases, the owner will not be server 0, so the read by rank 0 might be remotely accessing the metadata.
```
This seems to be indeed the case, as I find the following entries in the logs of the *second* server (there are no such records in the log of the first server):
```
tid=160496 @ unifyfs_inode_resolve_extent_chunks() [unifyfs_inode.c:536] resolving chunk request (gfid=420982989, offset=4840, length=384)
tid=160497 @ unifyfs_inode_resolve_extent_chunks() [unifyfs_inode.c:536] resolving chunk request (gfid=420982989, offset=4456, length=384)
tid=160504 @ unifyfs_inode_resolve_extent_chunks() [unifyfs_inode.c:536] resolving chunk request (gfid=420982989, offset=4072, length=384)
tid=160502 @ unifyfs_inode_resolve_extent_chunks() [unifyfs_inode.c:536] resolving chunk request (gfid=420982989, offset=3688, length=384)
```

Thus, in summary, it looks like the Server only responds correctly to client Ranks 2 and 3. Ranks 0 and 1 did not get a valid response to their read-requests. 

As a reminder, with the new-margotree branch, the execution of the code goes fine, but I get wrong data into the file if I do not have the call to H5Fflush in the application. And we do not have a way to add Adam´s automatic sync-after-write in that branch.

**Comment by adammoody** [comment]
This program tries to read from a file that has no data.  The code that looks up extents correctly reports that there are no extents.  As a result, ``out.num_locations = 0`` here, so that ``buf_sz=0``, which then causes ``margo_bulk_create`` to fail:
https://github.com/LLNL/UnifyFS/blob/c4c2faa5d5e954d59fe1279c1f3f32c319b80c6c/server/src/unifyfs_p2p_rpc.c#L432-L446

**Comment by clmendes** [comment]
So, three questions immediately occur to me:

1) Why do the two other ranks (2 and 3) present correct behavior in their read operation?

2) Why does a Unify execution of the same code, with the 4 procs in the same node, work correctly?

3) Why does the code without Unify work correctly with 2 nodes?

**Comment by clmendes** [comment]
Also, looking at the server logs, I see that LOGERR message in the logs of the first server, not in the logs of the second server who was actually handling the read requests:

```
unifyfsd.log.catalyst321:2020-11-29T10:45:26 tid=113335 @ unifyfs_invoke_find_extents_rpc() [unifyfs_p2p_rpc.c:445] margo_bulk_create() failed
unifyfsd.log.catalyst321:2020-11-29T10:45:26 tid=113334 @ unifyfs_invoke_find_extents_rpc() [unifyfs_p2p_rpc.c:445] margo_bulk_create() failed
unifyfsd.log.catalyst321:2020-11-29T10:45:27 tid=113335 @ unifyfs_invoke_find_extents_rpc() [unifyfs_p2p_rpc.c:445] margo_bulk_create() failed
```

**Comment by adammoody** [comment]
@clmendes, I think this should help https://github.com/LLNL/UnifyFS/pull/581

**Comment by adammoody** [comment]
It should be possible to reproduce this with a simple test case in which two clients procs run on two nodes (two servers), and each client tries to lseek and read from a new file (no data).  One of the clients will issue a remote extent lookup, which is the code path that was failing.  The client that does a local lookup will work -- it requires a remote lookup where no extents are returned.

**Comment by adammoody** [comment]
> 
> 
> So, three questions immediately occur to me:
> 
>     1. Why do the two other ranks (2 and 3) present correct behavior in their read operation?
> 
The client ranks running on the server that hosts the extents run through a different path, which is working.  In particular, those ranks execute the code in this branch:
https://github.com/LLNL/UnifyFS/blob/c4c2faa5d5e954d59fe1279c1f3f32c319b80c6c/server/src/unifyfs_p2p_rpc.c#L370-L380

>     2. Why does a Unify execution of the same code, with the 4 procs in the same node, work correctly?
In this case, all 4 client ranks execute the code above.

> 
>     3. Why does the code without Unify work correctly with 2 nodes?

What do you mean here?  I'm confused about this case.

**Comment by adammoody** [comment]
Really nice job in isolating this bug and boiling things down to a simple reproducer, @clmendes .  Your work up front made things very easy to debug from that point.

**Comment by clmendes** [comment]
@adammoody , thanks for offering a fix. I will test it still today.

My comment (3) above was made because, from your comments, I thought you were saying that the application was doing something bad (i.e. reading from a non-existing file). Hence my comment, meaning that this should not be wrong, because the code without Unify works fine, despite the file not existing yet.

**Comment by adammoody** [comment]
Oh, sorry for the confusion.  It is valid for a program to read from an empty file.  UnifyFS should have returned 0 from the read call in this case indicating that no data was read.  Instead we were returning an error condition.  I was just trying to describe the situation that leads to the buggy path in UnifyFS.
