### ISSUE TITLE
Dev branch build failing

### ISSUE THREAD

**Issue by CamStan** [LLNL/UnifyFS#608]
### Describe the problem you're observing

Been having build issues when trying to build locally. When I pushed the current `dev` branch to my forked repo, my Travis CI failed with the same error I'm getting locally. 

Cleared the cache and ran Travis CI on the `dev` branch of the main repo again and it suddenly failed. No differences on the branch from when it passed 4 days ago.

### Describe how to reproduce the problem

Build locally or run Travis CI.

Same `dev` branch:
- Passing build from 4 days ago: https://travis-ci.com/github/LLNL/UnifyFS/builds/217874158
- Current failing build: https://travis-ci.com/github/LLNL/UnifyFS/builds/218418169

### Include any warning or errors or releveant debugging data

```
libtool: link: gfortran -I/usr/lib/x86_64-linux-gnu/openmpi/include -I/usr/lib/x86_64-linux-gnu/openmpi/lib -I/usr/lib/x86_64-linux-gnu/openmpi/lib -I../../../../client/src -I../../../../common/src -g -O2 -o .libs/writeread-ftn writeread_ftn-writeread.o  -L/usr//lib -L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi ../../client/src/.libs/libunifyfsf.so -lrt -lm -Wl,-rpath -Wl,/home/travis/build/LLNL/UnifyFS/unifyfs-0.1.0-577-g9620621/_inst/lib
../../client/src/.libs/libunifyfsf.so: undefined reference to `unifyfs_unmount'
../../client/src/.libs/libunifyfsf.so: undefined reference to `unifyfs_mount'
collect2: error: ld returned 1 exit status
Makefile:1444: recipe for target 'writeread-ftn' failed
make[4]: *** [writeread-ftn] Error 1
make[4]: Leaving directory '/home/travis/build/LLNL/UnifyFS/unifyfs-0.1.0-577-g9620621/_build/sub/examples/src'
Makefile:398: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/travis/build/LLNL/UnifyFS/unifyfs-0.1.0-577-g9620621/_build/sub/examples'
Makefile:498: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/travis/build/LLNL/UnifyFS/unifyfs-0.1.0-577-g9620621/_build/sub'
Makefile:409: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/travis/build/LLNL/UnifyFS/unifyfs-0.1.0-577-g9620621/_build/sub'
Makefile:704: recipe for target 'distcheck' failed
make: *** [distcheck] Error 1
```

**Comment by CamStan** [comment]
Comparing those two logs linked above, and running locally, it appears our `configure` isn't finding GOTCHA and spath anymore for some reason. They are in `$PATH` and `$LD_LIBRARY_PATH` on my local machine, but getting same error.
```
checking for gotcha_wrap in -lgotcha... yes
checking for spath_strdup_reduce_str in -lspath... yes
```
vs
```
checking for gotcha_wrap in -lgotcha... no
configure: WARNING: couldn't find a suitable libgotcha, use --with-gotcha=PATH
checking for spath_strdup_reduce_str in -lspath... no
configure: WARNING: couldn't find a suitable libspath
```
Seems odd given the branch didn't change between these two builds.

**Comment by MichaelBrim** [comment]
Well, at least "missing gotcha" explains why it was only happening for the fortran writeread. libunifyfsf.so depends on libunifyfs_gotcha, but our configure.ac and client/src/Makefile.am isn't properly handling the situation where gotcha is not available but fortran is enabled.

**Comment by MichaelBrim** [comment]
I haven't been able to reproduce this build failure in my own environments (both spack-based and bootstrap-based).

**Comment by MichaelBrim** [comment]
Regarding PATH vs LD_LIBRARY_PATH inclusion, gotcha and spath are library only (they have no executables), so I wouldn't expect them to be added to PATH.

**Comment by MichaelBrim** [comment]
Also, LD_LIBRARY_PATH is used for execution-time loading of libraries. It is not used for compilation/linking. So even if the needed libraries are in your LD_LIBRARY_PATH, if your compile/link doesn't point to their installation using LDFLAGS, then they won't be found.

**Comment by sandrain** [comment]
I can also build without problems using `--enable-fortran`. It's not relevant to this, but I noticed that the build fails with `-j` option to make (starting from `-j 4`).

**Comment by CamStan** [comment]
How we were linking our dependencies seem to have been reliant on Spack setting `$LIBRARY_PATH` which changed in a recent Spack commit (https://github.com/spack/spack/pull/21699).

**Comment by MichaelBrim** [comment]
It seems like neither gotcha nor spath provide pkgconfig files, so we can't rely on PKG_CHECK_MODULES like we do for the margo dependency. I have been scanning the spack documentation looking for an easy way to retrieve the install root for a package, but so far am having no luck. If we had the install roots, we could just update our documentation and Travis build to use the roots to set CPPFLAGS and LDFLAGS on the configure command, similar to the change I recently made to bootstrap.sh

**Comment by CamStan** [comment]
@MichaelBrim, `spack location -I <package_name>` should do this (https://spack.readthedocs.io/en/latest/command_index.html#spack-location). It can be picky on the package name, especially if you have more than one installed. Sometimes have to include the variants in the name as well, but it seems to work well in environments.

So tried this and it build for me locally:
```
gotcha_location=$(spack location -i gotcha)
spath_location=$(spack location -i spath)

../configure --prefix=path/to/UnifyFS/install --enable-fortran --disable-silent-rules CPPFLAGS="-I${gotcha_location}/include -I${spath_location}/include" LDFLAGS="-L${gotcha_location}/lib64 -L${spath_location}/lib64"
```

**Comment by MichaelBrim** [comment]
So to summarize what we still need to fix:
1) Fix configure to complain when fortran and gotcha are enabled but gotcha is not found
2) Fix the client/src/Makefile.am to properly embed the HAVE_FORTRAN section within the HAVE_GOTCHA section
3) Optionally, use a specific tagged version of spack in Travis, rather than the latest code that occasionally breaks things for us
4) Update travis.yml to use the install locations for gotcha and spath during configure

Does this capture everything?

**Comment by CamStan** [comment]
Nothing else coming to mind at the moment.

I'm currently in the middle of getting 4 working and I can have a go at putting 1 and 2 in my branch as well.

I can be torn on 3 but the more I think through it, I think it would be worth doing on Travis.
From the looks of it, I believe Spack v0.16.1 (released 8 days ago) should have all our dependency changes we are currently using. The only update I'm seeing since then is the Mochi-margo package changed their repo urls and archived their old repo (https://github.com/spack/spack/pull/22029/files). Shouldn't be any problems grabbing the release we depend on from the archived repo for now though, yeah?
I can add this to my branch as well.

**Comment by CamStan** [comment]
@MichaelBrim, I just realized, v0.16.1 of Spack won't include the change that caused this whole break.

Do you think it would be better to stick with the Spack develop branch in Travis until their next release and still do number 4?
Or skip 4 for now and just mention it in our "Build dependencies with Spack, build UnifyFS with autotools" docs section for anyone using the Spack develop branch?

**Comment by MichaelBrim** [comment]
We should be able to do 4 regardless of which spack version we use in Travis. I would vote for using the latest tagged release of spack. And yes, we should also update the "building with spack" section of the user docs.

**Comment by CamStan** [comment]
Apparently the Spack releases don't always include the latest versions of the packages. The latest version (v0.16.1) doesn't have the `mochi-margo` packages, and the `margo` package there still only has version 0.4.3. Sticking with the develop branch for now, but I'll keep an eye out for updating this.

@MichaelBrim, after digging in a little, it appears our configure/makefiles are definitely missing some things.
I wanted to double check when we should work or shouldn't work in the combinations of GOTCHA and Fortran:

1. With GOTCHA, with Fortran
2. With GOTCHA, without Fortran
3. Without GOTCHA, with Fortran
4. Without GOTCHA, without Fortran

---

For 1 and 2, these are yes and are usually the cases we're testing against.

For 4:
I don't think I'd realized before, but it seems GOTCHA is meant to be an optional (but preferred) dependency for us, rather than required.
We do have `--with/without-gotcha` configure options, and our client/src/Makefile.am is set up to work without it.
So I'm assuming yes for 4, but we currently fail to build here as our examples/src/Makefile.am is not correctly handling the without GOTCHA case.

For 3:
I would still think yes, here, but above you stated:
> libunifyfsf.so depends on libunifyfs_gotcha, but our configure.ac and client/src/Makefile.am isn't properly handling the situation where gotcha is not available but fortran is enabled

I see that here:
https://github.com/LLNL/UnifyFS/blob/9620621aedb9d24338e86b20230646b6a510d4d7/client/src/Makefile.am#L87
but are we able to conditionally make this `libunifyfsf_la_LIBADD   = libunifyfs.la` if GOTCHA isn't available? Or is there something else I'm missing that makes it so we can only use Fortran if we have GOTCHA?

**Comment by CamStan** [comment]
Since I've asked, I might as well clarify a few others as well, haha.

Since UnifyFS itself longer depends on MPI (correct?), would the best solution when building without MPI be to just not build the examples/ and t/ directories? Or is that too broad?

It also appears our HDF5 examples expect to have GOTCHA, which also needs to be handled correctly in examples/src/Makefile.am. Not so much a clarification there I suppose.

**Comment by MichaelBrim** [comment]
Gotcha is (technically) an optional dependency. However, it is also the method that gives us the most functionality currently, since for example our MPI-IO support requires use of gotcha. 

For complete support of HDF5 (i.e., including parallel), we need MPI-IO support and thus gotcha. 

For Fortran, I'm not sure if we *really* need to use the libunifyfs_gotcha for linking libunifyfsf. There is a possibility that we could only capture the Fortran IO calls when using gotcha, but I don't remember if that was the case. My guess is we chose it because it was easier, not technically required. If we link libunifyfsf against libunifyfs, then the application must be link-wrapped in order for us see any of the IO calls.

**Comment by MichaelBrim** [comment]
Regarding MPI, I think it makes sense to keep it as a required dependency. The target platforms for deploying UnifyFS are all parallel computers supporting MPI, so I don't think it makes sense to reorganize our build infrastructure for the case where MPI is missing.

**Comment by sandrain** [comment]
@CamStan @MichaelBrim I've tested building with our `bootstrap.sh` script and failed to build unifyfs. Bootstrapping it self went fine without many problems, but I've encountered two problems while building unifyfs.

First, the last part of the bootstrap script:

```
if [ "$automake_sub_version" -lt "15" ] ; then
    echo -n "  export PKG_CONFIG_PATH=/usr/share/pkgconfig:/usr/lib64/pkgconfig:"
    echo "$INSTALL_DIR/lib/pkgconfig:\$PKG_CONFIG_PATH"
    echo "  export PATH=$INSTALL_DIR/bin:\$PATH"
else
    echo -n "  export PKG_CONFIG_PATH=$INSTALL_DIR/lib/pkgconfig:"
    echo "$INSTALL_DIR/lib64/pkgconfig:\$PKG_CONFIG_PATH"
fi
echo "  export LD_LIBRARY_PATH=$INSTALL_DIR/lib:\$LD_LIBRARY_PATH"

echo -n "  ./autogen.sh && ./configure --prefix=$INSTALL_DIR "
echo "CPPFLAGS=-I$INSTALL_DIR/include LDFLAGS=-L$INSTALL_DIR/lib"
```

In my build, both `lib` and `lib64` were used for installing libraries, but `LD_LIBRARY_PATH` and `PKG_CONFIG_PATH` didn't include `lib64` based paths. I had to manually add. Can we just include both by default? Is it problematic if some directory don't exist?

After that, `autogen` and `configure` went well, but `make` failed:

```
../../client/src/.libs/libunifyfs.a(libunifyfs_la-unifyfs-sysio.o): warning: the `getwd' function is dangerous and should not be used.
make[3]: Leaving directory `/autofs/nccs-svm1_proj/csc300/hs2/__tmp/bootstrap/UnifyFS/examples/src'
make[3]: Entering directory `/autofs/nccs-svm1_proj/csc300/hs2/__tmp/bootstrap/UnifyFS/examples'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/autofs/nccs-svm1_proj/csc300/hs2/__tmp/bootstrap/UnifyFS/examples'
make[2]: Leaving directory `/autofs/nccs-svm1_proj/csc300/hs2/__tmp/bootstrap/UnifyFS/examples'
Making all in extras
make[2]: Entering directory `/autofs/nccs-svm1_proj/csc300/hs2/__tmp/bootstrap/UnifyFS/extras'
cd .. && /bin/sh ./config.status extras/unifyfs.conf
config.status: creating extras/unifyfs.conf
make[2]: Leaving directory `/autofs/nccs-svm1_proj/csc300/hs2/__tmp/bootstrap/UnifyFS/extras'
Making all in t
make[2]: Entering directory `/autofs/nccs-svm1_proj/csc300/hs2/__tmp/bootstrap/UnifyFS/t'
Making all in lib
make[3]: Entering directory `/autofs/nccs-svm1_proj/csc300/hs2/__tmp/bootstrap/UnifyFS/t/lib'
  CC       tap.lo
  CCLD     libtap.la
  CC       testutil.lo
  CCLD     libtestutil.la
make[3]: Leaving directory `/autofs/nccs-svm1_proj/csc300/hs2/__tmp/bootstrap/UnifyFS/t/lib'
make[3]: Entering directory `/autofs/nccs-svm1_proj/csc300/hs2/__tmp/bootstrap/UnifyFS/t'
  CC       common_seg_tree_test_t-seg_tree_test.o
  CC       common_seg_tree_test_t-seg_tree.o
  CC       common_seg_tree_test_t-unifyfs_log.o
  CC       common_seg_tree_test_t-unifyfs_misc.o
  CCLD     common/seg_tree_test.t
  CC       common_slotmap_test_t-slotmap_test.o
  CC       common_slotmap_test_t-slotmap.o
  CCLD     common/slotmap_test.t
  CC       std_stdio_gotcha_t-stdio_suite.o
  CC       std_stdio_gotcha_t-fopen-fclose.o
  CC       std_stdio_gotcha_t-fseek-ftell.o
  CC       std_stdio_gotcha_t-fwrite-fread.o
  CC       std_stdio_gotcha_t-fflush.o
  CC       std_stdio_gotcha_t-size.o
make[3]: *** No rule to make target `../client/src/libunifyfs_gotcha.la', needed by `std/stdio-gotcha.t'.  Stop.
make[3]: Leaving directory `/autofs/nccs-svm1_proj/csc300/hs2/__tmp/bootstrap/UnifyFS/t'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/autofs/nccs-svm1_proj/csc300/hs2/__tmp/bootstrap/UnifyFS/t'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/autofs/nccs-svm1_proj/csc300/hs2/__tmp/bootstrap/UnifyFS'
make: *** [all] Error 2
```
I think it would be better if the script checks/warns the minimal requirements, e.g., compiler version, cmake, etc. Also, it could emit the `env.sh` file with all build/runtime environment vars included (e.g., `PKG_CONFIG_PATH`, `LD_LIBRARY_PATH`), so we can just source it (without having to copy & paste).

**Comment by CamStan** [comment]
Celso has been having problem getting this to work on our end as well. I'll play with it this week to help work out any issues and add your suggestions.

> In my build, both lib and lib64 were used for installing libraries, but LD_LIBRARY_PATH and PKG_CONFIG_PATH didn't include lib64 based paths. I had to manually add. Can we just include both by default? Is it problematic if some directory don't exist?

I believe it's find to include both here, even if one doesn't exist (speaking from my limited knowledge on the subject).

**Comment by CamStan** [comment]
Closed this. If the bootstrap script specifically is still causing issues, let's open a new issue.
