### ISSUE TITLE
Minor issue with current bootstrap script

### ISSUE THREAD

**Issue by clmendes** [LLNL/UnifyFS#618]
I did a new Unify build on Catalyst today, using the bootstrap script as I usually do, and observed a problem that might cause confusion in the future. There's an easy workaround, but I suspect fixing the script would be the ideal solution.

The problem is in the build steps that the script suggests at the end of its execution. This is what I get:

``` 
Dependencies are all built.  You can now build UnifyFS with:

  export PATH=/g/g12/mendes3/UnifyFS-611/UnifyFS/install/bin:$PATH
  export PKG_CONFIG_PATH=/usr/share/pkgconfig:/usr/lib64/pkgconfig:/g/g12/mendes3/UnifyFS-611/UnifyFS/install/lib/pkgconfig:/g/g12/mendes3/UnifyFS-611/UnifyFS/install/lib64/pkgconfig:$PKG_CONFIG_PATH
  export LD_LIBRARY_PATH=/g/g12/mendes3/UnifyFS-611/UnifyFS/install/lib:/g/g12/mendes3/UnifyFS-611/UnifyFS/install/lib64:$LD_LIBRARY_PATH
  ./autogen.sh
  ./configure --prefix=/g/g12/mendes3/UnifyFS-611/UnifyFS/install CPPFLAGS=-I/g/g12/mendes3/UnifyFS-611/UnifyFS/install/includeLDFLAGS="-L/g/g12/mendes3/UnifyFS-611/UnifyFS/install/lib -L/g/g12/mendes3/UnifyFS-611/UnifyFS/install/lib64"
  make && make install

```

So, it seems that there is a missing blank space before LDFLAGS. in the configure step. The workaround is simply to add the blank space manually, but I believe it would be good to have the script fixed.

This was observed using a fresh Unify version from dev, after Pull-Request #611, from a while ago.

**Comment by CamStan** [comment]
Agreed that a space should be there. @clmendes, were you already opening a PR for that?
