### ISSUE TITLE
Undefined reference to major() & minor()

### ISSUE THREAD

**Issue by rgmiller** [LLNL/UnifyFS#620]
On new-ish Linux distros (CentOS 8, Ubuntu 20.04), builds fail with errors about undefined references to `major()` and `minor()`.  There are also warnings about these functions having to be implicitly defined.  The functions are used in [examples/src/testlib.h](https://github.com/LLNL/UnifyFS/blob/dev/examples/src/testlib.h).

The basic problem is that these functions are (now) defined in `sys/sysmacros.h` and testlib.h doesn't include that header.  In older distributions, `sys/types.h` included `sys/sysmacros.h`, but that changed with glibc v2.28.

The fix is probably to just `#include <sys/sysmacros.h>` in testlib.h, but we need to make sure that won't break any older systems that we need to support.

Note: This was originally discussed in issue #609.  I'm creating a separate issue because #609 wasn't specifically about `major()` and `minor()`.

**Comment by CamStan** [comment]
Copying thoughts here for easy reference:

> From looking up other projects that have run into this, it looks like on newer glibc (starting at 2.25 I think) the major() and minor() macros are removed from sys/types.h and are only available in sys/sysmacros.h.
> Announcement here: https://sourceware.org/legacy-ml/libc-alpha/2015-11/msg00253.html
> 
> However, it also seems sys/sysmacros.h is a non-standard header and might not always be available. So may need to also include AC_HEADER_MAJOR (https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Particular-Headers.html) in our configure.ac.
> 
> However, some additional things might need to be done in addition to addingAC_HEADER_MAJOR since depending on the versions of things such as gcc, glibc, Red Hat, Slurm, and autoconf, who defines these macros first or at all could cause other problems.
> https://bugs.schedmd.com/show_bug.cgi?id=3982
> and
> https://lists.gnu.org/archive/html/autoconf-patches/2016-09/msg00008.html

**Comment by CamStan** [comment]
Spack issue just opened mentioning this: https://github.com/spack/spack/issues/23292

**Comment by adammoody** [comment]
So I'm wondering if we're even really using these two macros anymore.  We use those in testlib.h to print ``st_dev`` and ``st_rdev`` values:
https://github.com/LLNL/UnifyFS/blob/724d5b474024390e74fd889277e3556017ee917f/examples/src/testlib.h#L221
and:
https://github.com/LLNL/UnifyFS/blob/724d5b474024390e74fd889277e3556017ee917f/examples/src/testlib.h#L242

However, with grep, it looks to me like we just set those fields once and we always set them to 0:
https://github.com/LLNL/UnifyFS/blob/724d5b474024390e74fd889277e3556017ee917f/common/src/unifyfs_meta.h#L233
https://github.com/LLNL/UnifyFS/blob/724d5b474024390e74fd889277e3556017ee917f/common/src/unifyfs_meta.h#L238
with:
https://github.com/LLNL/UnifyFS/blob/724d5b474024390e74fd889277e3556017ee917f/common/src/unifyfs_meta.h#L82

If we're not really using these, we could just drop the macros the the lines that print the ``st_dev``/``st_rdev`` values.

**Comment by CamStan** [comment]
I think we were (are?) planning on phasing out of using _testlib.h_ as our newer examples use _testutil.h_.
However, we use those macros in _testutil.c_ also, so @MichaelBrim is probably the best to decide if we need to use those macros in the examples.
https://github.com/LLNL/UnifyFS/blob/724d5b474024390e74fd889277e3556017ee917f/examples/src/testutil.c#L15

---

But now that I look, it appears we're already doing `#include <sys/sysmacros>` in _testutil.c_, which the reported issue isn't complaining about. So @rgmiller's solution of just adding `#include <sys/sysmacros>` to _testlib.h_ might be the easiest solution.

I think I initially overthought this and went down the wrong rabbit hole in regards to `AC_HEADER_MAJOR`, which we don't have in our _configure.ac_ anyways.

**Comment by MichaelBrim** [comment]
I vote for just adding a configure check for existence of <sys/sysmacros.h> and #including it when it exists. We can address whether we really need to use the macros in the near-future when we remove all the tests based on testlib.h.

**Comment by rgmiller** [comment]
I just spent a little time trying out both methods.  In configure.ac, we can either do:
`AC_HEADER_MAJOR`
or:
`AC_CHECK_HEADER([sys/sysmacros.h], [], AC_MSG_ERROR([cannot find required header sys/sysmacros.h]))`

The second one will abort the `configure` script if `sys/sysmacros.h` doesn't exist.  The first will properly handle the various locations for `major()` and `minor()`, but we'll to add something like:
``` C
#include <config.h>
#if defined MAJOR_IN_MKDEV
    #include <sys/mkdev.h>
#elif defined MAJOR_IN_SYSMACROS
    #include <sys/sysmacros.h>
#endif
```
to the top of `testlib.h` (probably `testutil.c`, too).  

Does anyone have any strong preferences for one or the other?

**Comment by MichaelBrim** [comment]
@rgmiller Did you consider using `AC_CHECK_HEADERS`  or `AC_CHECK_HEADERS_ONCE` instead? With that, we could just use
```
#ifdef HAVE_SYS_SYSMACROS_H
# include <sys/sysmacros.h>
#endif

**Comment by rgmiller** [comment]
@MichaelBrim I *did*, but that seems like the worst of both worlds to me:  It doesn't totally fix the issue (ie: some systems apparently use `sys/mkdev.h`) and you still have to litter you headers with `#ifdef` blocks.

I'm leaning toward the `AC_HEADER_MAJOR` option.  That way, we know the issue is fixed once and for all and we don't have to think about it again.

**Comment by MichaelBrim** [comment]
@rgmiller I'm worried that AC_HEADER_MAJOR isn't bulletproof. See, for example, http://visa.lab.asu.edu/gitlab/fstrace/fstrace/commit/50608a4098dee3799791761dcba4d4453f95e8d2

I'm not really worried about non-Linux OS that use sys/mkdev.h, because we explicitly only support Linux

**Comment by MichaelBrim** [comment]
Yeah, I think that issue I linked only applied for a while until glibc fully transitioned to sys/sysmacros.h . 

So maybe use the AC_CHECK_HEADER() with error that you had above, and then just do the include without enclosing ifdef. That way, we'll catch it during configure if it's a weird system that's missing the header.

**Comment by rgmiller** [comment]
Everything is committed and merged.  Closing the issue.
