### ISSUE TITLE
bootstrap.sh lacks error checking

### ISSUE THREAD

**Issue by rgmiller** [LLNL/UnifyFS#633]
### System information

Type                   | Version/Name
---                    |     ---
Operating System      | Linux
OS Version             | RHEL 7.6
Architecture           | ppc64le  (summit.olcf.ornl.gov)
UnifyFS Version        | Git repo HEAD

### Describe the problem you're observing
`bootstrap.sh` seems to lack any error checking.  Even if it fails to properly build the dependencies, it still prints out its normal success message.

### Describe how to reproduce the problem

1. Log in to summit.olcf.ornl.gov.
2. *DO NOT* load the cmake module
3. Clone UnifyFS from the git repo
4. Run the bootstrap.sh script

### Include any warning or errors or releveant debugging data
This is a sample of the `bootstrap.sh` output:
```
checking pkg-config is at least version 0.9.0... yes
checking for MERCURY... no
configure: error: Could not find working mercury installation!
make: *** No targets specified and no makefile found.  Stop.
### building spath ###
Already on 'master'
./bootstrap.sh: line 249: cmake: command not found
make: *** No targets specified and no makefile found.  Stop.
*************************************************************************
Dependencies are all built.  You can now build UnifyFS with:

  export PATH=/ccs/home/xmr/git/UnifyFS/install/bin:$PATH
  export PKG_CONFIG_PATH=/usr/share/pkgconfig:/usr/lib64/pkgconfig:/ccs/home/xmr/git/UnifyFS/install/lib/pkgconfig:/ccs/home/xmr/git/UnifyFS/install/lib64/pkgconfig:$PKG_CONFIG_PATH
  export LD_LIBRARY_PATH=/ccs/home/xmr/git/UnifyFS/install/lib:/ccs/home/xmr/git/UnifyFS/install/lib64:$LD_LIBRARY_PATH
  ./autogen.sh
  ./configure --prefix=/ccs/home/xmr/git/UnifyFS/install CPPFLAGS=-I/ccs/home/xmr/git/UnifyFS/install/include LDFLAGS="-L/ccs/home/xmr/git/UnifyFS/install/lib -L/ccs/home/xmr/git/UnifyFS/install/lib64"
  make && make install

*************************************************************************
```
There's at least two problems shown in this output:

1. Mercury failed to build, but `bootstrap.sh` continued on to try and build spath.  This would arguably be acceptable behavior *IF* the failure to build Mercury was summarized at the end, but it's not.
2. Both Mercury and spath failed to build, but the summary text that `bootstrap.sh` prints at the end says everything is fine.

**Comment by MichaelBrim** [comment]
Fixed with #714, closing.
