### ISSUE TITLE
Write examples fail with default options and default spillover size

### ISSUE THREAD

**Issue by CamStan** [LLNL/UnifyFS#634]
### Describe the problem you're observing
Running the _write_ or _writeread_ examples (static or gotcha) on a single node and with a single process, using the default options and default `spill_size` (1 GiB), fails while trying to write MiB 318.

The example succeeds when increasing the `spill_size` to 2 GiB (possibly less).
 
The default values for these examples are:
https://github.com/LLNL/UnifyFS/blob/dcc3984f6de5b5d758388e22e1dbe57a13026c40/examples/src/testutil.h#L113-L115

and the default `shmem_size` and `spill_size` are:
https://github.com/LLNL/UnifyFS/blob/dcc3984f6de5b5d758388e22e1dbe57a13026c40/common/src/unifyfs_const.h#L79-L80

The expected behavior is that 512 MiB should fit within the default `shmem_size` and `spill_size`.

### Describe how to reproduce the problem
Get a single node allocation, set a few config options, and start the server:
```
export UNIFYFS_DAEMONIZE=off
export UNIFYFS_LOG_DIR=${MY_JOBDIR}/logs
export UNIFYFS_LOG_VERBOSITY=5
export UNIFYFS_LOGIO_SPILL_DIR=$NODE_LOCAL_STORAGE_PATH
export UNIFYFS_SHAREDFS_DIR=${MY_JOBDIR}/share

$UNIFYFS_INSTALL/bin/unifyfs start -d -S $UNIFYFS_SHAREDFS_DIR -e $UNIFYFS_INSTALL/bin/unifyfsd &> $UNIFYFS_LOG_DIR/unifyfs.start.out
```

Run the default `write-static` example with a single process:
```
jsrun -r1 -n1 -a1 -k $UNIFYFS_LOG_DIR/write-static-1GBspill.err -o $UNIFYFS_LOG_DIR/write-static-1GBspill.out $UNIFYFS_EXAMPLES/write-static
```

### Include any warning or errors or releveant debugging data

The stdout log for the client starts getting errors on write req 318 (each request here is 1MiB)
```
$ head ${UNIFYFS_LOG_DIR}/write-static-1GBspill.out
[0] write() failed (errno=28, No space left on device)
[0] write req 318 failed (errno=28, No space left on device)
[0] write() failed (errno=28, No space left on device)
[0] write req 319 failed (errno=28, No space left on device)
⋮
```

The client error log shows the last successful write of `1048576 bytes` at `pos=332398592`, with the following attempt failing
```
$ head -n 1333 write-static-1GBspill.err | tail -n 6
2021-05-27T16:08:50 tid=93764 @ unifyfs_intercept_fd() [unifyfs.c:349] Changing fd from exposed 16384 to internal 0
2021-05-27T16:08:50 tid=93764 @ unifyfs_fid_logio_write() [unifyfs-fixed.c:326] fid=1 pos=332398592 - successful logio_write() @ log offset=1333723136 (1048576 bytes)
2021-05-27T16:08:50 tid=93764 @ unifyfs_intercept_fd() [unifyfs.c:349] Changing fd from exposed 16384 to internal 0
2021-05-27T16:08:50 tid=93764 @ __wrap_write() [unifyfs-sysio.c:1444] write was called for fd 16384
2021-05-27T16:08:50 tid=93764 @ unifyfs_intercept_fd() [unifyfs.c:349] Changing fd from exposed 16384 to internal 0
2021-05-27T16:08:50 tid=93764 @ unifyfs_fid_logio_write() [unifyfs-fixed.c:309] logio_alloc(1048576) failed
```

The only thing that stood out to me in the server is that once these errors start, the server will continually log that it's waiting for work until the server is stopped.
```
70 2021-05-27T16:08:50 tid=93771 @ request_manager_thread() [unifyfs_request_manager.c:1390] RM[1511587981:1] waiting for work
71 2021-05-27T16:08:50 tid=93082 @ signal_new_requests() [unifyfs_request_manager.c:264] signaling new requests
72 2021-05-27T16:08:50 tid=93771 @ request_manager_thread() [unifyfs_request_manager.c:1403] RM[1511587981:1] got work
73 2021-05-27T16:08:50 tid=93771 @ rm_process_client_requests() [unifyfs_request_manager.c:1269] processing 1 client requests
74 2021-05-27T16:08:50 tid=93771 @ process_metaset_rpc() [unifyfs_request_manager.c:1109] setting metadata for gfid=579954078
75 2021-05-27T16:08:50 tid=93771 @ request_manager_thread() [unifyfs_request_manager.c:1390] RM[1511587981:1] waiting for work
76 2021-05-27T16:08:50 tid=93771 @ request_manager_thread() [unifyfs_request_manager.c:1390] RM[1511587981:1] waiting for work
77 2021-05-27T16:08:50 tid=93771 @ request_manager_thread() [unifyfs_request_manager.c:1390] RM[1511587981:1] waiting for work
78 2021-05-27T16:08:50 tid=93771 @ request_manager_thread() [unifyfs_request_manager.c:1390] RM[1511587981:1] waiting for work
   ⋮
4477 2021-05-27T16:09:35 tid=93771 @ request_manager_thread() [unifyfs_request_manager.c:1390] RM[1511587981:1] waiting for work
4478 2021-05-27T16:09:35 tid=93771 @ request_manager_thread() [unifyfs_request_manager.c:1390] RM[1511587981:1] waiting for work
4479 2021-05-27T16:09:35 tid=93074 @ exit_request() [unifyfs_server.c:156] exit requested
4480 2021-05-27T16:09:35 tid=93074 @ main() [unifyfs_server.c:420] starting service shutdown
```

---

After setting the `spill_size` to 2GiB and running again, the example succeeds:
```
I/O pattern:               N-to-1
I/O block size:            16384.00 KiB
I/O request size:          1024.00 KiB
Number of processes:       1
Each process wrote:        512.00 MiB
Total data written:        512.00 MiB
File create time:          0.000268 sec
Maximum write time:        0.037875 sec
Global write time:         0.037877 sec
Maximum sync time:         0.000953 sec
Global sync time:          0.000954 sec
File laminate time:        0.000742 sec
Full write time:           0.040569 sec
File stat time:            0.000170 sec
Aggregate write bandwidth: 13518.152 MiB/s
Effective write bandwidth: 13518.152 MiB/s
```

Credit to @HenryYihengXu for finding this

**Comment by MichaelBrim** [comment]
Yes, this is due to the default LOGIO_CHUNK_SIZE of 4 MiB, which results in 63 chunks available in shmem and 255 chunks in spillover (since we use a page at the beginning of each for the chunk usage map). We can either change the default sizes in `testutil.h` to fit, or we can adjust the LOGIO defaults. I would vote for bumping LOGIO_SPILL_SIZE up to a 4 GiB default.

**Comment by CamStan** [comment]
Ah, yes, that makes sense. Thank you! Agree on bumping LOGIO_SPILL_SIZE up.

**Comment by HenryYihengXu** [comment]
Yes increasing spill_size worked for me. But If at the same time I change [logio] spill_size in the config file to 4GB, the error shows up again.

**Comment by MichaelBrim** [comment]
@HenryYihengXu Which config file did you modify? Most of our users, including me, don't actually use the config file for setting defaults. Instead, I just modify the corresponding environment variable.

**Comment by HenryYihengXu** [comment]
I'm sorry that was a typo. I modified **chunk_size** to 4GB in $UNIFYFS_INSTALL/etc/unifyfs/unifyfs.conf. I also set UNIFYFS_CONFIGFILE to be that path.

I just tried using environment variables. If I just set UNIFYFS_LOGIO_SPILL_SIZE to be 5GB, it works. But if I set both UNIFYFS_LOGIO_SPILL_SIZE to be 5GB and UNIFYFS_LOGIO_CHUNK_SIZE to be 4GB, the no space error shows up again.

**Comment by MichaelBrim** [comment]
The chunk size should be a small value that corresponds somewhat closely with the size of individual write operations. So for the write and writeread examples, a good chunk size would be 1 MiB.

Setting it to something big means you only have room for one write operation. The total number of writes a client can perform is roughly `(UNIFYFS_LOGIO_SPILL_SIZE + UNIFYFS_LOGIO_SHMEM_SIZE)/UNIFYFS_LOGIO_CHUNK_SIZE`
