### ISSUE TITLE
Segfault in unifyfsd on shutdown

### ISSUE THREAD

**Issue by rgmiller** [LLNL/UnifyFS#646]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       | Linux
OS Version             | Ubuntu 
Architecture           | 20.04.2 LTS
UnifyFS Version        |  Git commit 2a0352a3 (June 4, 2021)

### Describe the problem you're observing
Given the correct set of conditions, unifyfsd will segfault during shutdown.
### Describe how to reproduce the problem
My test environment is a single Ubuntu workstation.  I start unifyfsd in one terminal window in non-daemon mode.  (I don't know if daemon vs. non-daemon is relevant, but I suspect it isn't.)  I then run a simple ior test (configured to write to /unifyfs) in another terminal window.  I'm not sure if it's relevant, but the ior job is actually mis-configured and exits with an MPI_ABORT call.  After ior finishes, kill unifyfsd either with `kill` or with a CTRL-C in the terminal where it's running.  The unifyfsd process will segfault.

### Include any warning or errors or relevant debugging data

I've been able to narrow this down to a free of a phread_cont_t from one thread while a separate thread is still waiting on that condition variable.  Note the following output from valgrind:
```
==50503== 
==50503== Syscall param futex(futex) points to unaddressable byte(s)
==50503==    at 0x4D4E7B1: futex_abstimed_wait_cancelable (futex-internal.h:320)
==50503==    by 0x4D4E7B1: __pthread_cond_wait_common (pthread_cond_wait.c:520)
==50503==    by 0x4D4E7B1: pthread_cond_timedwait@@GLIBC_2.3.2 (pthread_cond_wait.c:656)
==50503==    by 0x13B273: request_manager_thread (unifyfs_request_manager.c:1398)
==50503==    by 0x4D47608: start_thread (pthread_create.c:477)
==50503==    by 0x4E83292: clone (clone.S:95)
==50503==  Address 0x127e7f78 is 56 bytes inside a block of size 336,024 free'd
==50503==    at 0x483CA3F: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==50503==    by 0x13E12D: cleanup_app_client (unifyfs_server.c:970)
==50503==    by 0x13E280: cleanup_application (unifyfs_server.c:724)
==50503==    by 0x10DB9B: unifyfs_exit (unifyfs_server.c:605)
==50503==    by 0x10DB9B: main (unifyfs_server.c:431)
==50503==  Block was alloc'd at
==50503==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==50503==    by 0x137C85: unifyfs_rm_thrd_create (unifyfs_request_manager.c:94)
==50503==    by 0x13E449: new_app_client (unifyfs_server.c:826)
==50503==    by 0x12856F: unifyfs_mount_rpc (unifyfs_cmd_handler.c:90)
==50503==    by 0x12884C: _wrapper_for_unifyfs_mount_rpc (unifyfs_cmd_handler.c:122)
==50503==    by 0x48DBF5D: ABTD_ythread_func_wrapper (in /home/xmr/git/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/argobots-1.1-hisrkaviwllaag5e5lrfyobgmyz4ufsz/lib/libabt.so.1.1.0)
==50503==    by 0x48DC100: make_fcontext (in /home/xmr/git/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/argobots-1.1-hisrkaviwllaag5e5lrfyobgmyz4ufsz/lib/libabt.so.1.1.0)
```

The call to `pthread_cond_timedwait()` happens repeatedly in a loop (10ms timeout on the wait).  If I set breakpoints on the call to `free()` in `cleanup_app_client()` and on the loop exit check, I can see that the call to `free()` is happening while the other thread is still inside `pthread_cond_timedwait()`.

**Comment by MichaelBrim** [comment]
I think this is related to (or is the same problem as) #567. Jenna's work on the client heartbeat RPC is one part of the solution (identifying clients that failed to properly unmount and terminating their associated reqmgr thread).

**Comment by rgmiller** [comment]
Yeah, OK.  After reading #567, it does sound like this issue is at least related.

**Comment by rgmiller** [comment]
Worth noting: The reproducer I noted above no longer causes a segfault starting with commit 47c144c8 ("build separate libraries for mpi-mount", June 11).  This is a pretty big commit, but I don't see any changes to the server code in it.  For now, I'm going to assume the race condition still exists but that code changes are affecting the timing enough that we're just not hitting the bug any more.

**Comment by rgmiller** [comment]
I haven't been able to reproduce this issue in a long time.  Closing the issue.
