### ISSUE TITLE
Cannot build with gcc 11

### ISSUE THREAD

**Issue by ARMartinelli** [LLNL/UnifyFS#647]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       |  Arch Linux
UnifyFS Version        |  last

### Describe the problem you're observing
I cannot build UnifyFS with gcc 11.1.0.
### Describe how to reproduce the problem
For the build I followed the docs (https://unifyfs.readthedocs.io/en/latest/build.html#build-dependencies-with-bootstrap-and-build-unifyfs-with-autotools)
### Include any warning or errors or releveant debugging data
This is the error message:

../../common/src/tinyexpr.c: In function ‘base’:
../../common/src/tinyexpr.c:314:16: error: array subscript ‘te_expr[0]’ is partly outside array bounds of ‘unsigned char[16]’ [-Werror=array-bounds]
  314 |             ret->bound = s->bound;
      |                ^~
../../common/src/tinyexpr.c:88:20: note: referencing an object of size 16 allocated by ‘malloc’
   88 |     te_expr *ret = malloc(size);
      |                    ^~~~~~~~~~~~
../../common/src/tinyexpr.c:93:15: error: array subscript ‘te_expr[0]’ is partly outside array
bounds of ‘unsigned char[16]’ [-Werror=array-bounds]
   93 |     ret->type = type;
      |     ~~~~~~~~~~^~~~~~
../../common/src/tinyexpr.c:88:20: note: referencing an object of size 16 allocated by ‘malloc’
   88 |     te_expr *ret = malloc(size);
      |                    ^~~~~~~~~~~~
../../common/src/tinyexpr.c:308:16: error: array subscript ‘te_expr[0]’ is partly outside array bounds of ‘unsigned char[16]’ [-Werror=array-bounds]
  308 |             ret->value = s->value;
      |                ^~
../../common/src/tinyexpr.c:88:20: note: referencing an object of size 16 allocated by ‘malloc’
   88 |     te_expr *ret = malloc(size);
      |                    ^~~~~~~~~~~~
../../common/src/tinyexpr.c:387:16: error: array subscript ‘te_expr[0]’ is partly outside array bounds of ‘unsigned char[16]’ [-Werror=array-bounds]
  387 |             ret->value = NAN;
      |                ^~
../../common/src/tinyexpr.c:88:20: note: referencing an object of size 16 allocated by ‘malloc’
   88 |     te_expr *ret = malloc(size);

**Comment by rgmiller** [comment]
I can confirm this.  I see the same problem building on Ubuntu 20.04LTS with gcc 11.1.0.

I'm guessing that gcc 11 is smarter about error checking than gcc 10 was, and that's why we haven't seen this problem before.

**Comment by MichaelBrim** [comment]
We should try to update common/src/tinyexpr.[ch] based on the current code at https://github.com/codeplea/tinyexpr to see if the newer code makes gcc11 happy.
