### ISSUE TITLE
unifyfs_fskv_init() can return success without actually initializing the K/V store

### ISSUE THREAD

**Issue by rgmiller** [LLNL/UnifyFS#652]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       | Linux
OS Version             | Ubuntu 20.04 LTS
Architecture           | x86_64
UnifyFS Version        | HEAD of dev branch

I suspect this affects all OS's and architectures.

### Describe the problem you're observing
If you start unifyfsd without the -S parameter (which is admittedly an incorrect thing to do), the code will make it all the way through `unifyfs_fskv_init()` without actually initializing the K/V store.  Furthermore, `unifyfs_fskv_init()` returns `UNIFYFS_SUCCESS` in this case.  unifyfsd then fails the first time the K/V store is used.

### Describe how to reproduce the problem
Start unifyfsd without the -S parameter.

### Include any warning or errors or relevant debugging data

The error returned from unifyfsd is
```
2021-07-23T16:44:18 tid=62736 @ unifyfs_keyval_publish_remote() [../../common/src/unifyfs_keyval.c:1047] remote keyval publish for 'unifyfsd.pmi-rank' failed
```
which comes from the first time unifyfsd tries to use `unifyfs_keyval_publish_remote()`.

**Comment by adammoody** [comment]
@rgmiller , thanks for the fix.  Does that cover this issue?

**Comment by rgmiller** [comment]
@adammoody Yes, it does.  I need to close the issue.

**Comment by rgmiller** [comment]
Pull request #654 fixes this issue.
