### ISSUE TITLE
Generated `configure` file looking for unrecoginized option `-showconfig` when configuring `h5pcc`/`mpicc` compilers

### ISSUE THREAD

**Issue by kwryankrattiger** [LLNL/UnifyFS#674]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       | fedora
OS Version             | 33
Architecture           | x86_64
UnifyFS Version        | 0.9.2

Type                   | Version/Name
---                    |     ---
System       | Spock@ORNL
Architecture           | zen2

### Describe the problem you're observing

During configuration there is an unrecognized option passed to the compiler wrappers for HDF5/MPI `-showconfig`.

I have done some digging and this is not an officially documented option anywhere. Judging from the contents of the configure file it is attempting to capture the HDF5 version from this option, but the `h5pcc` does not process that option at all, much less provide a method of getting the Version string.

### Describe how to reproduce the problem

If you would like, I could generate a container for reproducing this issue.

When building with spack@develop

Package | Implementations
--- | ---
MPI | mpich@3.4.2, cray-mpich@8.1.11
Compiler | oneapi@2021.3.0, gcc@11.2.0

Spec:
`unifyfs@0.9.2+auto-mount~fortran+hdf5~pmi~pmix+spath`

### Include any warning or errors or releveant debugging data

```
==> Error: ProcessError: Command exited with status 2:
    'make' 'V=1'

3 errors found in build log:
     203    checking whether the inttypes.h PRIxNN macros are broken... no
     204    checking whether byte ordering is bigendian... no
     205    checking for off64_t... yes
     206    checking if linker supports -wrap... yes
     207    checking Using provided HDF5 C wrapper... /cwd/opt/spack/linux-fedora33-skylake/oneapi-
            2021.3.0/hdf5-1.10.7-fogspmziwewhetadxywsq7j3tjq66q37/bin/h5pcc
     208    checking for HDF5 type... parallel
  >> 209    checking for HDF5 libraries... clang: error: unknown argument: '-showconfig'
  >> 210    clang: error: unknown argument: '-showconfig'
  >> 211    clang: error: unknown argument: '-showconfig'
     212    yes (version )
     213    checking hdf5.h usability... no
     214    checking hdf5.h presence... yes
     215    configure: WARNING: hdf5.h: present but cannot be compiled
     216    configure: WARNING: hdf5.h:     check for missing prerequisite headers?
     217    configure: WARNING: hdf5.h: see the Autoconf documentation
```

Edit Jan 20, 2020: Added cray-mpich and GCC as failing to configure on Spock for the same reason

**Comment by CamStan** [comment]
We have since removed the misleading `+hdf5` variant from our spack package. Nothing special needs to happen during build to be compatible with HDF5. If UnifyFS still won't configure/build without that variant, please reopen.
