### ISSUE TITLE
read requests complete successfully but EINPROGRESS still set

### ISSUE THREAD

**Issue by roblatham00** [LLNL/UnifyFS#681]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       | Ubuntu
OS Version             | 20.04.1
Architecture           | x86_64
UnifyFS Version        | head

### Describe the problem you're observing

i post several write operations and a SYNC_META operation.  these complete sucessfully.  Then I issue a few read operations.  These appear to complete succesfully (dispatch and wait return SUCESS) but the error code is non-zero (EINPROGRESS)

### Describe how to reproduce the problem

Run the test case here:  https://gist.github.com/roblatham00/ed209f95af446f2ac8bbed5f93ffcfa1  I took out any MPI  things: just needs a single client talking to a single unify server.

### Include any warning or errors or releveant debugging data

Here's the output when I loop through the requests looking at error codes:

```
error in request 0: 0x73 Operation now in progress
error in request 1: 0x73 Operation now in progress
error in request 2: 0x73 Operation now in progress
error in request 3: 0x73 Operation now in progress
error in request 4: 0x73 Operation now in progress
error in request 5: 0x73 Operation now in progress
```

Since I'm checking the error status of every operation, ROMIO sees these spurious errors and aborts .

**Comment by MichaelBrim** [comment]
@roblatham00 I'm not able to reproduce this in my Ubuntu Docker container with latest dev. Can you check again with current HEAD of dev?

**Comment by roblatham00** [comment]
thanks for checking.  sorry for the false alarm.  Agreed, HEAD fixes this issue.   I'll close this issue.  

Still have the issue where error code is not being set on success:  I see I only emailed you about that, so I opened  https://github.com/LLNL/UnifyFS/issues/682 .
