### ISSUE TITLE
no way to convey "exclusive create"

### ISSUE THREAD

**Issue by roblatham00** [LLNL/UnifyFS#689]
### System information

Type                   | Version/Name
---                    |     ---
Operating System       | Linux
OS Version             | Ubuntu 21.04
Architecture           | x86_64
UnifyFS Version        | -devel

### Describe the problem you're observing

There appears to be no way to convey, through the Unify client api, the notion of "exclusive create" -- "Create this file but fail if it already exists".    The O_EXCL|O_CREAT flag to open(2) or the MPI-IO flag MPI_MODE_EXCL|MPI_MODE_CREATE

### Proposed solution
`unifyfs_create` has a `flags` field but it is presently reserved.    Either use that parameter or add a new parameter to express how we'd like create to behave.

**Comment by MichaelBrim** [comment]
@roblatham00 `unifyfs_create()` should be exclusive by default, in that it should return EEXIST if the file already exists. If that's not the case, then this is indeed a bug.

**Comment by roblatham00** [comment]
since I misunderstood unify_create semantics, I'll close this issue and open a new one
