### ISSUE TITLE
Error while building unifyfs version 0.9.2 using spack

### ISSUE THREAD

**Issue by hariharan-devarajan** [LLNL/UnifyFS#718]
### System information
Type                   | Version/Name
---                    |     ---
Operating System       | ubuntu
OS Version             | 18.04
Architecture           | x86_64
UnifyFS Version        | 0.9.2

### Describe the problem you're observing
The latest spack packages have a new version of mochi-margo 0.9.10. In this version, the libraries are renamed. The current build of unifyfs version 0.9.2 works with mochi-margo 0.9.6. However, the docs mention only mochi-margo which defaults to latest. Can you please update the doc to reflect this version? For your reference, here is the spec I used for a successful installation of unifyfs@0.9.2 with spack version 0.19.0.dev0.

NOTE: I have the SDS repo (https://github.com/mochi-hpc/mochi-spack-packages) from mochi developers as I use thallium for my projects. They have conflicting packages between spack builtin and SDS repo. Please add that warning note in the docs for users.

### Describe how to reproduce the problem

To reproduce checkout the latest spack packages (I tried with commit 1c0bf12e5b21de3d77af2b1025479d30c4c94400) and install unifyfs.

### Error

We see that configure is not able to find margo lib. It has been renamed from libmargo.so to libmochi-margo.so.

**Comment by CamStan** [comment]
Spack package has been updated (https://github.com/spack/spack/pull/32625) and should resolve the remainder of this issue.
